Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_1:
      Precision:
        result: fixed<16,6>
      Trace: false
    q_activation:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_1:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_2:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_3:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: fixed<16,6>
        slope: fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: fixed<16,6>
        bias: fixed<8,3>
        result: fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_1:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: fixed<16,6>
        bias: fixed<8,3>
        result: fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_1_linear:
      Precision:
        result: fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_2:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: fixed<16,6>
        bias: fixed<8,3>
        result: fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_2_linear:
      Precision:
        result: fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_3:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: fixed<16,6>
        bias: fixed<8,3>
        result: fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_3_linear:
      Precision:
        result: fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_linear:
      Precision:
        result: fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'model_final/keras_model.h5'
OutputDir: model_final
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: BeCFA7BA
Version: 1.0.0
