// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer19_out_din,
        layer19_out_num_data_valid,
        layer19_out_fifo_cap,
        layer19_out_full_n,
        layer19_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [191:0] layer4_out_dout;
input  [7:0] layer4_out_num_data_valid;
input  [7:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [191:0] layer19_out_din;
input  [7:0] layer19_out_num_data_valid;
input  [7:0] layer19_out_fifo_cap;
input   layer19_out_full_n;
output   layer19_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg[191:0] layer19_out_din;
reg layer19_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer19_out_blk_n;
wire    ap_CS_fsm_state3;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_done;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_idle;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_ready;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer4_out_read;
wire   [191:0] grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_din;
wire    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_write;
reg    grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg;
reg    ap_block_state1_ignore_call3;
wire    ap_CS_fsm_state2;
reg   [2:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg = 1'b0;
end

myproject_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start),
    .ap_done(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_done),
    .ap_idle(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_idle),
    .ap_ready(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(8'd0),
    .layer4_out_fifo_cap(8'd0),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer4_out_read),
    .layer19_out_din(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_din),
    .layer19_out_num_data_valid(8'd0),
    .layer19_out_fifo_cap(8'd0),
    .layer19_out_full_n(layer19_out_full_n),
    .layer19_out_write(grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_ready == 1'b1)) begin
            grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer19_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer19_out_blk_n = layer19_out_full_n;
    end else begin
        layer19_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer19_out_din = 192'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer19_out_din = grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_din;
    end else begin
        layer19_out_din = grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_din;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer19_out_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer19_out_write = grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer19_out_write;
    end else begin
        layer19_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer4_out_read = grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_layer4_out_read;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call3 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start = grp_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_Pipeline_CopyMain_fu_30_ap_start_reg;

assign start_out = real_start;

endmodule //myproject_zeropad1d_cl_array_array_ap_ufixed_6_0_4_0_0_32u_config19_s
