Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_13:
      Precision:
        result: ap_fixed<16,10>
      Trace: false
    q_activation_60:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_61:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_62:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_63:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_64:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: ap_fixed<16,10>
        slope: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_60:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_60_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_61:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_61_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_62:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_62_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_63:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_63_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_64:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_64_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,10>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'dil_150_unpruned_8<16,10>/keras_model.h5'
OutputDir: dil_150_unpruned_8<16,10>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: CADBf4EE
Version: 1.0.0
