-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_compute_output_buffer_1d_array_array_ap_fixed_27_12_5_3_0_32u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    layer2_out_din : OUT STD_LOGIC_VECTOR (863 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer2_out_full_n : IN STD_LOGIC;
    layer2_out_write : OUT STD_LOGIC;
    layer2_out_blk_n : OUT STD_LOGIC );
end;


architecture behav of myproject_compute_output_buffer_1d_array_array_ap_fixed_27_12_5_3_0_32u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_52 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_32 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal and_ln350_reg_349 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln350_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal select_ln376_fu_164_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln369_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_out_reg_361 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal res_out_1_reg_366 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_2_reg_371 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_3_reg_376 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_4_reg_381 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_5_reg_386 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_6_reg_391 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_7_reg_396 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_8_reg_401 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_9_reg_406 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_10_reg_411 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_11_reg_416 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_12_reg_421 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_13_reg_426 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_14_reg_431 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_15_reg_436 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_16_reg_441 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_17_reg_446 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_18_reg_451 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_19_reg_456 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_20_reg_461 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_21_reg_466 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_22_reg_471 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_23_reg_476 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_24_reg_481 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_25_reg_486 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_26_reg_491 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_27_reg_496 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_28_reg_501 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_29_reg_506 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_30_reg_511 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_out_31_reg_516 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_1 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_2 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_3 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_4 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_5 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_6 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_7 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_8 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_9 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_10 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_11 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_12 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_13 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_14 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_15 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_16 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_17 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_18 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_19 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_20 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_21 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_22 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_23 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_24 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_25 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_26 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_27 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_28 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_29 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_30 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_31 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_ce : STD_LOGIC;
    signal ap_block_state2_pp0_stage1_iter0_ignore_call0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp19 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_ignore_call0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_ignoreCallOp29 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_reg_57 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln369_fu_140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_769_fu_118_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln350_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln350_1_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln376_fu_158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_228 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_32 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68 : component myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_32 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_32,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30,
        ap_return_0 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_3,
        ap_return_4 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_4,
        ap_return_5 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_5,
        ap_return_6 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_6,
        ap_return_7 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_7,
        ap_return_8 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_8,
        ap_return_9 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_9,
        ap_return_10 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_10,
        ap_return_11 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_11,
        ap_return_12 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_12,
        ap_return_13 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_13,
        ap_return_14 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_14,
        ap_return_15 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_15,
        ap_return_16 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_16,
        ap_return_17 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_17,
        ap_return_18 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_18,
        ap_return_19 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_19,
        ap_return_20 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_20,
        ap_return_21 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_21,
        ap_return_22 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_22,
        ap_return_23 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_23,
        ap_return_24 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_24,
        ap_return_25 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_25,
        ap_return_26 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_26,
        ap_return_27 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_27,
        ap_return_28 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_28,
        ap_return_29 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_29,
        ap_return_30 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_30,
        ap_return_31 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_31,
        ap_ce => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_storemerge_reg_57_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_228)) then
                if ((icmp_ln369_fu_146_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_57 <= ap_const_lv32_0;
                elsif ((icmp_ln369_fu_146_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_57 <= select_ln376_fu_164_p3;
                end if;
            end if; 
        end if;
    end process;

    pX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_228)) then
                if ((icmp_ln369_fu_146_p2 = ap_const_lv1_1)) then 
                    pX_3 <= ap_const_lv32_0;
                elsif ((icmp_ln369_fu_146_p2 = ap_const_lv1_0)) then 
                    pX_3 <= add_ln369_fu_140_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                and_ln350_reg_349 <= and_ln350_fu_134_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln350_reg_349) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                res_out_10_reg_411 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_10;
                res_out_11_reg_416 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_11;
                res_out_12_reg_421 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_12;
                res_out_13_reg_426 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_13;
                res_out_14_reg_431 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_14;
                res_out_15_reg_436 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_15;
                res_out_16_reg_441 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_16;
                res_out_17_reg_446 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_17;
                res_out_18_reg_451 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_18;
                res_out_19_reg_456 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_19;
                res_out_1_reg_366 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_1;
                res_out_20_reg_461 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_20;
                res_out_21_reg_466 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_21;
                res_out_22_reg_471 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_22;
                res_out_23_reg_476 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_23;
                res_out_24_reg_481 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_24;
                res_out_25_reg_486 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_25;
                res_out_26_reg_491 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_26;
                res_out_27_reg_496 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_27;
                res_out_28_reg_501 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_28;
                res_out_29_reg_506 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_29;
                res_out_2_reg_371 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_2;
                res_out_30_reg_511 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_30;
                res_out_31_reg_516 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_31;
                res_out_3_reg_376 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_3;
                res_out_4_reg_381 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_4;
                res_out_5_reg_386 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_5;
                res_out_6_reg_391 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_6;
                res_out_7_reg_396 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_7;
                res_out_8_reg_401 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_8;
                res_out_9_reg_406 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_9;
                res_out_reg_361 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                sX_3 <= ap_phi_reg_pp0_iter0_storemerge_reg_57;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30 <= in_elem_0_0_0_0_0_val;
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_30;
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_32 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln369_fu_140_p2 <= std_logic_vector(unsigned(pX_3) + unsigned(ap_const_lv32_1));
    add_ln376_fu_158_p2 <= std_logic_vector(unsigned(sX_3) + unsigned(ap_const_lv32_1));
    and_ln350_fu_134_p2 <= (icmp_ln350_fu_108_p2 and icmp_ln350_1_fu_128_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, layer2_out_full_n, and_ln350_reg_349)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_const_lv1_1 = and_ln350_reg_349) and (layer2_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, layer2_out_full_n, and_ln350_reg_349)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_lv1_1 = and_ln350_reg_349) and (layer2_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_ce, layer2_out_full_n, and_ln350_reg_349)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_const_lv1_1 = and_ln350_reg_349) and (layer2_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001_ignoreCallOp19 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001_ignoreCallOp29 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(layer2_out_full_n, and_ln350_reg_349)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((ap_const_lv1_1 = and_ln350_reg_349) and (layer2_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_228_assign_proc : process(ap_enable_reg_pp0_iter0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_228 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_ignoreCallOp19, ap_block_pp0_stage2_11001_ignoreCallOp29)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_ignoreCallOp29) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp19) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))))) then 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_27_12_5_3_0_config2_mult_s_fu_68_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln350_1_fu_128_p2 <= "1" when (signed(tmp_769_fu_118_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln350_fu_108_p2 <= "1" when (sX_3 = ap_const_lv32_2) else "0";
    icmp_ln369_fu_146_p2 <= "1" when (add_ln369_fu_140_p2 = ap_const_lv32_52) else "0";

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer2_out_full_n, ap_block_pp0_stage0, and_ln350_reg_349)
    begin
        if (((ap_const_lv1_1 = and_ln350_reg_349) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_full_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer2_out_din <= (((((((((((((((((((((((((((((((res_out_31_reg_516 & res_out_30_reg_511) & res_out_29_reg_506) & res_out_28_reg_501) & res_out_27_reg_496) & res_out_26_reg_491) & res_out_25_reg_486) & res_out_24_reg_481) & res_out_23_reg_476) & res_out_22_reg_471) & res_out_21_reg_466) & res_out_20_reg_461) & res_out_19_reg_456) & res_out_18_reg_451) & res_out_17_reg_446) & res_out_16_reg_441) & res_out_15_reg_436) & res_out_14_reg_431) & res_out_13_reg_426) & res_out_12_reg_421) & res_out_11_reg_416) & res_out_10_reg_411) & res_out_9_reg_406) & res_out_8_reg_401) & res_out_7_reg_396) & res_out_6_reg_391) & res_out_5_reg_386) & res_out_4_reg_381) & res_out_3_reg_376) & res_out_2_reg_371) & res_out_1_reg_366) & res_out_reg_361);

    layer2_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, and_ln350_reg_349, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_1 = and_ln350_reg_349) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_write <= ap_const_logic_1;
        else 
            layer2_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln376_fu_164_p3 <= 
        ap_const_lv32_2 when (icmp_ln350_fu_108_p2(0) = '1') else 
        add_ln376_fu_158_p2;
    tmp_769_fu_118_p4 <= pX_3(31 downto 1);
end behav;
