-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_hard_sigmoid_array_array_ap_ufixed_8_0_4_0_0_1u_hard_sigmoid_config17_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer15_out_dout : IN STD_LOGIC_VECTOR (19 downto 0);
    layer15_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer15_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer15_out_empty_n : IN STD_LOGIC;
    layer15_out_read : OUT STD_LOGIC;
    layer17_out_TREADY : IN STD_LOGIC;
    layer17_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    layer17_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of myproject_hard_sigmoid_array_array_ap_ufixed_8_0_4_0_0_1u_hard_sigmoid_config17_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_50 : STD_LOGIC_VECTOR (6 downto 0) := "1010000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv22_1000 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_const_lv14_1000 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_const_lv22_2000 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv14_2000 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal regslice_both_layer17_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln448_fu_107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer15_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer17_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal datareg_fu_148_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal datareg_reg_319 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln458_1_fu_154_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln458_1_reg_325 : STD_LOGIC_VECTOR (13 downto 0);
    signal i_fu_82 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_18_fu_113_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_17 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shl_ln_fu_124_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln458_fu_136_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln458_fu_132_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln458_3_fu_140_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln459_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_165_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln459_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln459_fu_172_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal datareg_1_fu_186_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln463_fu_219_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_764_fu_203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln463_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln463_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_765_fu_211_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln463_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_193_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln463_fu_241_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_766_fu_251_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln463_fu_245_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_768_fu_273_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_767_fu_265_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln463_1_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln463_1_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln463_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln463_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal layer17_out_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal layer17_out_TVALID_int_regslice : STD_LOGIC;
    signal layer17_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_layer17_out_U_vld_out : STD_LOGIC;
    signal ap_condition_117 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_layer17_out_U : component myproject_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => layer17_out_TDATA_int_regslice,
        vld_in => layer17_out_TVALID_int_regslice,
        ack_in => layer17_out_TREADY_int_regslice,
        data_out => layer17_out_TDATA,
        vld_out => regslice_both_layer17_out_U_vld_out,
        ack_out => layer17_out_TREADY,
        apdone_blk => regslice_both_layer17_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_117)) then
                if ((icmp_ln448_fu_107_p2 = ap_const_lv1_0)) then 
                    i_fu_82 <= i_18_fu_113_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_82 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    add_ln458_1_reg_325(13 downto 1) <= add_ln458_1_fu_154_p2(13 downto 1);
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    datareg_reg_319(21 downto 1) <= datareg_fu_148_p2(21 downto 1);
            end if;
        end if;
    end process;
    datareg_reg_319(0) <= '0';
    add_ln458_1_reg_325(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln458_1_fu_154_p2 <= std_logic_vector(unsigned(trunc_ln458_3_fu_140_p3) + unsigned(ap_const_lv14_1000));
    add_ln463_fu_245_p2 <= std_logic_vector(unsigned(trunc_ln_fu_193_p4) + unsigned(zext_ln463_fu_241_p1));
    and_ln463_1_fu_293_p2 <= (xor_ln463_fu_259_p2 and or_ln463_1_fu_287_p2);
    and_ln463_fu_235_p2 <= (tmp_765_fu_211_p3 and or_ln463_fu_229_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_done_reg, layer15_out_empty_n, regslice_both_layer17_out_U_apdone_blk, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int, layer17_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (layer17_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1) or (layer17_out_TREADY_int_regslice = ap_const_logic_0))) or ((layer15_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_done_reg, layer15_out_empty_n, regslice_both_layer17_out_U_apdone_blk, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int, layer17_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (layer17_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1) or (layer17_out_TREADY_int_regslice = ap_const_logic_0))) or ((layer15_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_done_reg, layer15_out_empty_n, regslice_both_layer17_out_U_apdone_blk, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int, layer17_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (layer17_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1) or (layer17_out_TREADY_int_regslice = ap_const_logic_0))) or ((layer15_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer15_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer15_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(regslice_both_layer17_out_U_apdone_blk, layer17_out_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_layer17_out_U_apdone_blk = ap_const_logic_1) or (layer17_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(layer17_out_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (layer17_out_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_117_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_117 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln448_fu_107_p2, ap_start_int)
    begin
        if (((icmp_ln448_fu_107_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_17_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_82, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_17 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_17 <= i_fu_82;
        end if; 
    end process;

    datareg_1_fu_186_p3 <= 
        select_ln459_fu_172_p3 when (or_ln459_fu_180_p2(0) = '1') else 
        add_ln458_1_reg_325;
    datareg_fu_148_p2 <= std_logic_vector(signed(sext_ln458_fu_132_p1) + signed(ap_const_lv22_1000));
    i_18_fu_113_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_17) + unsigned(ap_const_lv7_1));
    icmp_ln448_fu_107_p2 <= "1" when (ap_sig_allocacmp_i_17 = ap_const_lv7_50) else "0";
    icmp_ln459_fu_160_p2 <= "1" when (signed(datareg_reg_319) > signed(ap_const_lv22_2000)) else "0";
    icmp_ln463_fu_223_p2 <= "0" when (trunc_ln463_fu_219_p1 = ap_const_lv4_0) else "1";

    layer15_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer15_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer15_out_blk_n <= layer15_out_empty_n;
        else 
            layer15_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer15_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer15_out_read <= ap_const_logic_1;
        else 
            layer15_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, layer17_out_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            layer17_out_TDATA_blk_n <= layer17_out_TREADY_int_regslice;
        else 
            layer17_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer17_out_TDATA_int_regslice <= 
        add_ln463_fu_245_p2 when (and_ln463_1_fu_293_p2(0) = '1') else 
        ap_const_lv8_FF;
    layer17_out_TVALID <= regslice_both_layer17_out_U_vld_out;

    layer17_out_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer17_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            layer17_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln459_fu_180_p2 <= (tmp_fu_165_p3 or icmp_ln459_fu_160_p2);
    or_ln463_1_fu_287_p2 <= (xor_ln463_1_fu_281_p2 or tmp_767_fu_265_p3);
    or_ln463_fu_229_p2 <= (tmp_764_fu_203_p3 or icmp_ln463_fu_223_p2);
    select_ln459_fu_172_p3 <= 
        ap_const_lv14_2000 when (icmp_ln459_fu_160_p2(0) = '1') else 
        ap_const_lv14_0;
        sext_ln458_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_124_p3),22));

    shl_ln_fu_124_p3 <= (layer15_out_dout & ap_const_lv1_0);
    tmp_764_fu_203_p3 <= datareg_1_fu_186_p3(5 downto 5);
    tmp_765_fu_211_p3 <= datareg_1_fu_186_p3(4 downto 4);
    tmp_766_fu_251_p3 <= datareg_1_fu_186_p3(13 downto 13);
    tmp_767_fu_265_p3 <= add_ln463_fu_245_p2(7 downto 7);
    tmp_768_fu_273_p3 <= datareg_1_fu_186_p3(12 downto 12);
    tmp_fu_165_p3 <= datareg_reg_319(21 downto 21);
    trunc_ln458_3_fu_140_p3 <= (trunc_ln458_fu_136_p1 & ap_const_lv1_0);
    trunc_ln458_fu_136_p1 <= layer15_out_dout(13 - 1 downto 0);
    trunc_ln463_fu_219_p1 <= datareg_1_fu_186_p3(4 - 1 downto 0);
    trunc_ln_fu_193_p4 <= datareg_1_fu_186_p3(12 downto 5);
    xor_ln463_1_fu_281_p2 <= (tmp_768_fu_273_p3 xor ap_const_lv1_1);
    xor_ln463_fu_259_p2 <= (tmp_766_fu_251_p3 xor ap_const_lv1_1);
    zext_ln463_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln463_fu_235_p2),8));
end behav;
