-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_conv_1d_cl_array_array_ap_fixed_23_12_5_3_0_32u_config12_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer21_out_dout : IN STD_LOGIC_VECTOR (383 downto 0);
    layer21_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer21_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer21_out_empty_n : IN STD_LOGIC;
    layer21_out_read : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer12_out_din : OUT STD_LOGIC_VECTOR (735 downto 0);
    layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    layer12_out_full_n : IN STD_LOGIC;
    layer12_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_conv_1d_cl_array_array_ap_fixed_23_12_5_3_0_32u_config12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_52 : STD_LOGIC_VECTOR (6 downto 0) := "1010010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110100";
    constant ap_const_lv32_179 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111001";
    constant ap_const_lv32_17A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111010";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_65 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100101";
    constant ap_const_lv32_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100110";
    constant ap_const_lv32_6B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101011";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_71 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110001";
    constant ap_const_lv32_72 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110010";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000100";
    constant ap_const_lv32_89 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001001";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011011";
    constant ap_const_lv32_9C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011100";
    constant ap_const_lv32_A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100001";
    constant ap_const_lv32_A2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100010";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101101";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111001";
    constant ap_const_lv32_BA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111010";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_C5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000101";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_CB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001011";
    constant ap_const_lv32_CC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001100";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011000";
    constant ap_const_lv32_DD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011101";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_E3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100011";
    constant ap_const_lv32_E4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100100";
    constant ap_const_lv32_E9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101001";
    constant ap_const_lv32_EA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101010";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110101";
    constant ap_const_lv32_F6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110110";
    constant ap_const_lv32_FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111011";
    constant ap_const_lv32_FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111100";
    constant ap_const_lv32_101 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000001";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_107 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000111";
    constant ap_const_lv32_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001000";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_113 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010011";
    constant ap_const_lv32_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010100";
    constant ap_const_lv32_119 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011001";
    constant ap_const_lv32_11A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011010";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_125 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100101";
    constant ap_const_lv32_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100110";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_131 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110001";
    constant ap_const_lv32_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110010";
    constant ap_const_lv32_137 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110111";
    constant ap_const_lv32_138 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111000";
    constant ap_const_lv32_13D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111101";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_143 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000011";
    constant ap_const_lv32_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000100";
    constant ap_const_lv32_149 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001001";
    constant ap_const_lv32_14A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001010";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_155 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010101";
    constant ap_const_lv32_156 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010110";
    constant ap_const_lv32_15B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011011";
    constant ap_const_lv32_15C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011100";
    constant ap_const_lv32_161 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100001";
    constant ap_const_lv32_162 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100010";
    constant ap_const_lv32_167 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100111";
    constant ap_const_lv32_168 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101000";
    constant ap_const_lv32_16D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101101";
    constant ap_const_lv32_16E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101110";
    constant ap_const_lv32_173 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln22_reg_1876 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n : STD_LOGIC;
    signal ap_block_state9_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal layer21_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal layer12_out_blk_n : STD_LOGIC;
    signal icmp_ln22_fu_1154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din : STD_LOGIC_VECTOR (735 downto 0);
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write : STD_LOGIC;
    signal ap_block_state2_pp0_stage1_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_state9_pp0_stage1_iter1_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp87 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_ignoreCallOp88 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state4_pp0_stage3_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_ignoreCallOp89 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_ignoreCallOp90 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_state6_pp0_stage5_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_ignoreCallOp91 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_state7_pp0_stage6_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_ignoreCallOp92 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call68 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1_ignore_call68 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp93 : BOOLEAN;
    signal grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal i_iw_01_fu_678 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_iw_4_fu_1160_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_iw : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_269 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read40 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read41 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read43 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read44 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read45 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read47 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read48 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read49 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read51 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read52 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read53 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read55 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read56 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read57 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read59 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read60 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read61 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read63 : IN STD_LOGIC_VECTOR (5 downto 0);
        layer12_out_din : OUT STD_LOGIC_VECTOR (735 downto 0);
        layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer12_out_full_n : IN STD_LOGIC;
        layer12_out_write : OUT STD_LOGIC;
        layer12_out_blk_n : OUT STD_LOGIC );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688 : component myproject_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start,
        ap_done => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_done,
        ap_idle => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_idle,
        ap_ready => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready,
        ap_ce => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce,
        p_read => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read,
        p_read1 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1,
        p_read2 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2,
        p_read3 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3,
        p_read4 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4,
        p_read5 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5,
        p_read6 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6,
        p_read7 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7,
        p_read8 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8,
        p_read9 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9,
        p_read10 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10,
        p_read11 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11,
        p_read12 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12,
        p_read13 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13,
        p_read14 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14,
        p_read15 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15,
        p_read16 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16,
        p_read17 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17,
        p_read18 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18,
        p_read19 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19,
        p_read20 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20,
        p_read21 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21,
        p_read22 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22,
        p_read23 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23,
        p_read24 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24,
        p_read25 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25,
        p_read26 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26,
        p_read27 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27,
        p_read28 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28,
        p_read29 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29,
        p_read30 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30,
        p_read31 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31,
        p_read32 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32,
        p_read33 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33,
        p_read34 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34,
        p_read35 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35,
        p_read36 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36,
        p_read37 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37,
        p_read38 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38,
        p_read39 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39,
        p_read40 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40,
        p_read41 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41,
        p_read42 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42,
        p_read43 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43,
        p_read44 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44,
        p_read45 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45,
        p_read46 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46,
        p_read47 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47,
        p_read48 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48,
        p_read49 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49,
        p_read50 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50,
        p_read51 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51,
        p_read52 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52,
        p_read53 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53,
        p_read54 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54,
        p_read55 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55,
        p_read56 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56,
        p_read57 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57,
        p_read58 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58,
        p_read59 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59,
        p_read60 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60,
        p_read61 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61,
        p_read62 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62,
        p_read63 => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63,
        layer12_out_din => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din,
        layer12_out_num_data_valid => ap_const_lv8_0,
        layer12_out_fifo_cap => ap_const_lv8_0,
        layer12_out_full_n => layer12_out_full_n,
        layer12_out_write => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write,
        layer12_out_blk_n => grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage6_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln22_fu_1154_p2 = ap_const_lv1_0))) then 
                    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_iw_01_fu_678_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_269)) then
                if ((icmp_ln22_fu_1154_p2 = ap_const_lv1_0)) then 
                    i_iw_01_fu_678 <= i_iw_4_fu_1160_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_iw_01_fu_678 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln22_reg_1876 <= icmp_ln22_fu_1154_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage6_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp93_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp93 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, layer21_out_empty_n, icmp_ln22_reg_1876, grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n)
    begin
                ap_block_pp0_stage1_11001 <= (((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln22_reg_1876 = ap_const_lv1_0) and (layer21_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_11001_ignoreCallOp87_assign_proc : process(ap_enable_reg_pp0_iter0, layer21_out_empty_n, icmp_ln22_reg_1876)
    begin
                ap_block_pp0_stage1_11001_ignoreCallOp87 <= ((icmp_ln22_reg_1876 = ap_const_lv1_0) and (layer21_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, layer21_out_empty_n, icmp_ln22_reg_1876, grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n)
    begin
                ap_block_pp0_stage1_subdone <= (((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln22_reg_1876 = ap_const_lv1_0) and (layer21_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_done_reg)
    begin
                ap_block_pp0_stage2_11001 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_pp0_stage2_11001_ignoreCallOp88_assign_proc : process(ap_done_reg)
    begin
                ap_block_pp0_stage2_11001_ignoreCallOp88 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_done_reg)
    begin
                ap_block_pp0_stage2_subdone <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001_ignoreCallOp89 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001_ignoreCallOp90 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001_ignoreCallOp91 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001_ignoreCallOp92 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call68_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call68 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(layer21_out_empty_n, icmp_ln22_reg_1876)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((icmp_ln22_reg_1876 = ap_const_lv1_0) and (layer21_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage1_iter0_ignore_call68_assign_proc : process(layer21_out_empty_n, icmp_ln22_reg_1876)
    begin
                ap_block_state2_pp0_stage1_iter0_ignore_call68 <= ((icmp_ln22_reg_1876 = ap_const_lv1_0) and (layer21_out_empty_n = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage6_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage6_iter0_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter1_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage1_iter1_assign_proc : process(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n)
    begin
                ap_block_state9_pp0_stage1_iter1 <= (grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n = ap_const_logic_0);
    end process;

        ap_block_state9_pp0_stage1_iter1_ignore_call68 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_269_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_269 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln22_reg_1876, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln22_reg_1876 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage6_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_iw_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, i_iw_01_fu_678, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_iw <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_iw <= i_iw_01_fu_678;
        end if; 
    end process;


    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage1_11001_ignoreCallOp87, ap_block_pp0_stage2_11001_ignoreCallOp88, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage3_11001_ignoreCallOp89, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage4_11001_ignoreCallOp90, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage5_11001_ignoreCallOp91, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage6_11001_ignoreCallOp92, ap_block_pp0_stage0_11001_ignoreCallOp93)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp93) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001_ignoreCallOp92) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001_ignoreCallOp91) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001_ignoreCallOp90) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001_ignoreCallOp89) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001_ignoreCallOp88) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp87) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce <= ap_const_logic_1;
        else 
            grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start <= grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg;
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read <= layer21_out_dout(6 - 1 downto 0);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1 <= layer21_out_dout(11 downto 6);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10 <= layer21_out_dout(65 downto 60);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11 <= layer21_out_dout(71 downto 66);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12 <= layer21_out_dout(77 downto 72);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13 <= layer21_out_dout(83 downto 78);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14 <= layer21_out_dout(89 downto 84);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15 <= layer21_out_dout(95 downto 90);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16 <= layer21_out_dout(101 downto 96);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17 <= layer21_out_dout(107 downto 102);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18 <= layer21_out_dout(113 downto 108);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19 <= layer21_out_dout(119 downto 114);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2 <= layer21_out_dout(17 downto 12);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20 <= layer21_out_dout(125 downto 120);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21 <= layer21_out_dout(131 downto 126);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22 <= layer21_out_dout(137 downto 132);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23 <= layer21_out_dout(143 downto 138);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24 <= layer21_out_dout(149 downto 144);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25 <= layer21_out_dout(155 downto 150);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26 <= layer21_out_dout(161 downto 156);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27 <= layer21_out_dout(167 downto 162);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28 <= layer21_out_dout(173 downto 168);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29 <= layer21_out_dout(179 downto 174);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3 <= layer21_out_dout(23 downto 18);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30 <= layer21_out_dout(185 downto 180);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31 <= layer21_out_dout(191 downto 186);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32 <= layer21_out_dout(197 downto 192);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33 <= layer21_out_dout(203 downto 198);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34 <= layer21_out_dout(209 downto 204);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35 <= layer21_out_dout(215 downto 210);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36 <= layer21_out_dout(221 downto 216);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37 <= layer21_out_dout(227 downto 222);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38 <= layer21_out_dout(233 downto 228);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39 <= layer21_out_dout(239 downto 234);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4 <= layer21_out_dout(29 downto 24);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40 <= layer21_out_dout(245 downto 240);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41 <= layer21_out_dout(251 downto 246);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42 <= layer21_out_dout(257 downto 252);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43 <= layer21_out_dout(263 downto 258);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44 <= layer21_out_dout(269 downto 264);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45 <= layer21_out_dout(275 downto 270);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46 <= layer21_out_dout(281 downto 276);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47 <= layer21_out_dout(287 downto 282);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48 <= layer21_out_dout(293 downto 288);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49 <= layer21_out_dout(299 downto 294);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5 <= layer21_out_dout(35 downto 30);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50 <= layer21_out_dout(305 downto 300);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51 <= layer21_out_dout(311 downto 306);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52 <= layer21_out_dout(317 downto 312);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53 <= layer21_out_dout(323 downto 318);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54 <= layer21_out_dout(329 downto 324);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55 <= layer21_out_dout(335 downto 330);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56 <= layer21_out_dout(341 downto 336);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57 <= layer21_out_dout(347 downto 342);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58 <= layer21_out_dout(353 downto 348);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59 <= layer21_out_dout(359 downto 354);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6 <= layer21_out_dout(41 downto 36);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60 <= layer21_out_dout(365 downto 360);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61 <= layer21_out_dout(371 downto 366);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62 <= layer21_out_dout(377 downto 372);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63 <= layer21_out_dout(383 downto 378);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7 <= layer21_out_dout(47 downto 42);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8 <= layer21_out_dout(53 downto 48);
    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9 <= layer21_out_dout(59 downto 54);
    i_iw_4_fu_1160_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_iw) + unsigned(ap_const_lv7_1));
    icmp_ln22_fu_1154_p2 <= "1" when (ap_sig_allocacmp_i_iw = ap_const_lv7_52) else "0";

    layer12_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer12_out_blk_n <= grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n;
        else 
            layer12_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer12_out_din <= grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din;

    layer12_out_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer12_out_write <= grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write;
        else 
            layer12_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer21_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, layer21_out_empty_n, icmp_ln22_reg_1876, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln22_reg_1876 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer21_out_blk_n <= layer21_out_empty_n;
        else 
            layer21_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer21_out_read_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln22_reg_1876, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln22_reg_1876 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer21_out_read <= ap_const_logic_1;
        else 
            layer21_out_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
