// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_conv_1d_cl_array_array_ap_fixed_23_12_5_3_0_32u_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer21_out_dout,
        layer21_out_num_data_valid,
        layer21_out_fifo_cap,
        layer21_out_empty_n,
        layer21_out_read,
        start_out,
        start_write,
        layer12_out_din,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer12_out_full_n,
        layer12_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 7'd1;
parameter    ap_ST_fsm_pp0_stage1 = 7'd2;
parameter    ap_ST_fsm_pp0_stage2 = 7'd4;
parameter    ap_ST_fsm_pp0_stage3 = 7'd8;
parameter    ap_ST_fsm_pp0_stage4 = 7'd16;
parameter    ap_ST_fsm_pp0_stage5 = 7'd32;
parameter    ap_ST_fsm_pp0_stage6 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [383:0] layer21_out_dout;
input  [7:0] layer21_out_num_data_valid;
input  [7:0] layer21_out_fifo_cap;
input   layer21_out_empty_n;
output   layer21_out_read;
output   start_out;
output   start_write;
output  [735:0] layer12_out_din;
input  [7:0] layer12_out_num_data_valid;
input  [7:0] layer12_out_fifo_cap;
input   layer12_out_full_n;
output   layer12_out_write;

reg ap_idle;
reg layer21_out_read;
reg start_write;
reg layer12_out_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln22_reg_1876;
reg    ap_block_state2_pp0_stage1_iter0;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n;
reg    ap_block_state9_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_subdone;
reg    layer21_out_blk_n;
wire    ap_block_pp0_stage1;
reg    layer12_out_blk_n;
wire   [0:0] icmp_ln22_fu_1154_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_done;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_idle;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready;
reg    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62;
wire   [5:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63;
wire   [735:0] grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din;
wire    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write;
reg    ap_block_state2_pp0_stage1_iter0_ignore_call68;
wire    ap_block_state9_pp0_stage1_iter1_ignore_call68;
reg    ap_block_pp0_stage1_11001_ignoreCallOp87;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call68;
reg    ap_block_pp0_stage2_11001_ignoreCallOp88;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call68;
wire    ap_block_pp0_stage3_11001_ignoreCallOp89;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state5_pp0_stage4_iter0_ignore_call68;
wire    ap_block_pp0_stage4_11001_ignoreCallOp90;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state6_pp0_stage5_iter0_ignore_call68;
wire    ap_block_pp0_stage5_11001_ignoreCallOp91;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state7_pp0_stage6_iter0_ignore_call68;
wire    ap_block_pp0_stage6_11001_ignoreCallOp92;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call68;
wire    ap_block_state8_pp0_stage0_iter1_ignore_call68;
reg    ap_block_pp0_stage0_11001_ignoreCallOp93;
reg    grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg;
reg    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage2;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
reg   [6:0] i_iw_01_fu_678;
wire   [6:0] i_iw_4_fu_1160_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_iw;
wire    ap_block_pp0_stage0;
wire    ap_continue_int;
reg    ap_done_int;
reg   [6:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_269;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start),
    .ap_done(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_done),
    .ap_idle(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_idle),
    .ap_ready(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready),
    .ap_ce(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce),
    .p_read(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read),
    .p_read1(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1),
    .p_read2(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2),
    .p_read3(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3),
    .p_read4(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4),
    .p_read5(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5),
    .p_read6(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6),
    .p_read7(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7),
    .p_read8(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8),
    .p_read9(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9),
    .p_read10(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10),
    .p_read11(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11),
    .p_read12(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12),
    .p_read13(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13),
    .p_read14(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14),
    .p_read15(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15),
    .p_read16(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16),
    .p_read17(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17),
    .p_read18(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18),
    .p_read19(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19),
    .p_read20(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20),
    .p_read21(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21),
    .p_read22(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22),
    .p_read23(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23),
    .p_read24(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24),
    .p_read25(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25),
    .p_read26(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26),
    .p_read27(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27),
    .p_read28(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28),
    .p_read29(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29),
    .p_read30(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30),
    .p_read31(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31),
    .p_read32(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32),
    .p_read33(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33),
    .p_read34(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34),
    .p_read35(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35),
    .p_read36(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36),
    .p_read37(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37),
    .p_read38(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38),
    .p_read39(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39),
    .p_read40(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40),
    .p_read41(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41),
    .p_read42(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42),
    .p_read43(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43),
    .p_read44(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44),
    .p_read45(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45),
    .p_read46(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46),
    .p_read47(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47),
    .p_read48(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48),
    .p_read49(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49),
    .p_read50(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50),
    .p_read51(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51),
    .p_read52(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52),
    .p_read53(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53),
    .p_read54(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54),
    .p_read55(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55),
    .p_read56(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56),
    .p_read57(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57),
    .p_read58(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58),
    .p_read59(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59),
    .p_read60(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60),
    .p_read61(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61),
    .p_read62(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62),
    .p_read63(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63),
    .layer12_out_din(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din),
    .layer12_out_num_data_valid(8'd0),
    .layer12_out_fifo_cap(8'd0),
    .layer12_out_full_n(layer12_out_full_n),
    .layer12_out_write(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write),
    .layer12_out_blk_n(grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln22_fu_1154_p2 == 1'd0))) begin
            grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_269)) begin
        if ((icmp_ln22_fu_1154_p2 == 1'd0)) begin
            i_iw_01_fu_678 <= i_iw_4_fu_1160_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_iw_01_fu_678 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln22_reg_1876 <= icmp_ln22_fu_1154_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln22_reg_1876 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_iw = 7'd0;
    end else begin
        ap_sig_allocacmp_i_iw = i_iw_01_fu_678;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp93) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001_ignoreCallOp92) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp91) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp90) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp89) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp88) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp87) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce = 1'b1;
    end else begin
        grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer12_out_blk_n = grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer12_out_write = grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_write;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (icmp_ln22_reg_1876 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer21_out_blk_n = layer21_out_empty_n;
    end else begin
        layer21_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln22_reg_1876 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer21_out_read = 1'b1;
    end else begin
        layer21_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp93 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln22_reg_1876 == 1'd0) & (layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp87 = ((icmp_ln22_reg_1876 == 1'd0) & (layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln22_reg_1876 == 1'd0) & (layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp88 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp89 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_ignoreCallOp90 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001_ignoreCallOp91 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001_ignoreCallOp92 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call68 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln22_reg_1876 == 1'd0) & (layer21_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_ignore_call68 = ((icmp_ln22_reg_1876 == 1'd0) & (layer21_out_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0_ignore_call68 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1_ignore_call68 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage1_iter1 = (grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_blk_n == 1'b0);
end

assign ap_block_state9_pp0_stage1_iter1_ignore_call68 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_269 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start = grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_ap_start_reg;

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read = layer21_out_dout[5:0];

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read1 = {{layer21_out_dout[11:6]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read10 = {{layer21_out_dout[65:60]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read11 = {{layer21_out_dout[71:66]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read12 = {{layer21_out_dout[77:72]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read13 = {{layer21_out_dout[83:78]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read14 = {{layer21_out_dout[89:84]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read15 = {{layer21_out_dout[95:90]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read16 = {{layer21_out_dout[101:96]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read17 = {{layer21_out_dout[107:102]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read18 = {{layer21_out_dout[113:108]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read19 = {{layer21_out_dout[119:114]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read2 = {{layer21_out_dout[17:12]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read20 = {{layer21_out_dout[125:120]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read21 = {{layer21_out_dout[131:126]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read22 = {{layer21_out_dout[137:132]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read23 = {{layer21_out_dout[143:138]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read24 = {{layer21_out_dout[149:144]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read25 = {{layer21_out_dout[155:150]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read26 = {{layer21_out_dout[161:156]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read27 = {{layer21_out_dout[167:162]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read28 = {{layer21_out_dout[173:168]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read29 = {{layer21_out_dout[179:174]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read3 = {{layer21_out_dout[23:18]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read30 = {{layer21_out_dout[185:180]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read31 = {{layer21_out_dout[191:186]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read32 = {{layer21_out_dout[197:192]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read33 = {{layer21_out_dout[203:198]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read34 = {{layer21_out_dout[209:204]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read35 = {{layer21_out_dout[215:210]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read36 = {{layer21_out_dout[221:216]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read37 = {{layer21_out_dout[227:222]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read38 = {{layer21_out_dout[233:228]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read39 = {{layer21_out_dout[239:234]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read4 = {{layer21_out_dout[29:24]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read40 = {{layer21_out_dout[245:240]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read41 = {{layer21_out_dout[251:246]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read42 = {{layer21_out_dout[257:252]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read43 = {{layer21_out_dout[263:258]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read44 = {{layer21_out_dout[269:264]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read45 = {{layer21_out_dout[275:270]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read46 = {{layer21_out_dout[281:276]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read47 = {{layer21_out_dout[287:282]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read48 = {{layer21_out_dout[293:288]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read49 = {{layer21_out_dout[299:294]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read5 = {{layer21_out_dout[35:30]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read50 = {{layer21_out_dout[305:300]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read51 = {{layer21_out_dout[311:306]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read52 = {{layer21_out_dout[317:312]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read53 = {{layer21_out_dout[323:318]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read54 = {{layer21_out_dout[329:324]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read55 = {{layer21_out_dout[335:330]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read56 = {{layer21_out_dout[341:336]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read57 = {{layer21_out_dout[347:342]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read58 = {{layer21_out_dout[353:348]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read59 = {{layer21_out_dout[359:354]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read6 = {{layer21_out_dout[41:36]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read60 = {{layer21_out_dout[365:360]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read61 = {{layer21_out_dout[371:366]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read62 = {{layer21_out_dout[377:372]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read63 = {{layer21_out_dout[383:378]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read7 = {{layer21_out_dout[47:42]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read8 = {{layer21_out_dout[53:48]}};

assign grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_p_read9 = {{layer21_out_dout[59:54]}};

assign i_iw_4_fu_1160_p2 = (ap_sig_allocacmp_i_iw + 7'd1);

assign icmp_ln22_fu_1154_p2 = ((ap_sig_allocacmp_i_iw == 7'd82) ? 1'b1 : 1'b0);

assign layer12_out_din = grp_compute_output_buffer_1d_array_array_ap_fixed_23_12_5_3_0_32u_config12_s_fu_688_layer12_out_din;

assign start_out = real_start;

endmodule //myproject_conv_1d_cl_array_array_ap_fixed_23_12_5_3_0_32u_config12_s
