// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_ufixed_6_0_4_0_0_32u_relu_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer5_out_dout,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_empty_n,
        layer5_out_read,
        layer7_out_din,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer7_out_full_n,
        layer7_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [703:0] layer5_out_dout;
input  [6:0] layer5_out_num_data_valid;
input  [6:0] layer5_out_fifo_cap;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [191:0] layer7_out_din;
input  [6:0] layer7_out_num_data_valid;
input  [6:0] layer7_out_fifo_cap;
input   layer7_out_full_n;
output   layer7_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer5_out_read;
reg layer7_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_529_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer5_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer7_out_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [703:0] layer5_out_read_reg_5126;
wire   [0:0] icmp_ln51_fu_860_p2;
reg   [0:0] icmp_ln51_reg_5162;
wire   [5:0] add_ln52_fu_918_p2;
reg   [5:0] add_ln52_reg_5167;
wire   [0:0] icmp_ln52_128_fu_934_p2;
reg   [0:0] icmp_ln52_128_reg_5173;
wire   [0:0] icmp_ln51_64_fu_940_p2;
reg   [0:0] icmp_ln51_64_reg_5178;
wire   [5:0] add_ln52_64_fu_1004_p2;
reg   [5:0] add_ln52_64_reg_5183;
wire   [0:0] icmp_ln52_130_fu_1020_p2;
reg   [0:0] icmp_ln52_130_reg_5189;
wire   [0:0] icmp_ln51_65_fu_1026_p2;
reg   [0:0] icmp_ln51_65_reg_5194;
wire   [5:0] add_ln52_65_fu_1090_p2;
reg   [5:0] add_ln52_65_reg_5199;
wire   [0:0] icmp_ln52_132_fu_1106_p2;
reg   [0:0] icmp_ln52_132_reg_5205;
wire   [0:0] icmp_ln51_66_fu_1112_p2;
reg   [0:0] icmp_ln51_66_reg_5210;
wire   [5:0] add_ln52_66_fu_1176_p2;
reg   [5:0] add_ln52_66_reg_5215;
wire   [0:0] icmp_ln52_134_fu_1192_p2;
reg   [0:0] icmp_ln52_134_reg_5221;
wire   [0:0] icmp_ln51_67_fu_1198_p2;
reg   [0:0] icmp_ln51_67_reg_5226;
wire   [5:0] add_ln52_67_fu_1262_p2;
reg   [5:0] add_ln52_67_reg_5231;
wire   [0:0] icmp_ln52_136_fu_1278_p2;
reg   [0:0] icmp_ln52_136_reg_5237;
wire   [0:0] icmp_ln51_68_fu_1284_p2;
reg   [0:0] icmp_ln51_68_reg_5242;
wire   [5:0] add_ln52_68_fu_1348_p2;
reg   [5:0] add_ln52_68_reg_5247;
wire   [0:0] icmp_ln52_138_fu_1364_p2;
reg   [0:0] icmp_ln52_138_reg_5253;
wire   [0:0] icmp_ln51_69_fu_1370_p2;
reg   [0:0] icmp_ln51_69_reg_5258;
wire   [5:0] add_ln52_69_fu_1434_p2;
reg   [5:0] add_ln52_69_reg_5263;
wire   [0:0] icmp_ln52_140_fu_1450_p2;
reg   [0:0] icmp_ln52_140_reg_5269;
wire   [0:0] icmp_ln51_70_fu_1456_p2;
reg   [0:0] icmp_ln51_70_reg_5274;
wire   [5:0] add_ln52_70_fu_1520_p2;
reg   [5:0] add_ln52_70_reg_5279;
wire   [0:0] icmp_ln52_142_fu_1536_p2;
reg   [0:0] icmp_ln52_142_reg_5285;
wire   [0:0] icmp_ln51_71_fu_1542_p2;
reg   [0:0] icmp_ln51_71_reg_5290;
wire   [5:0] add_ln52_71_fu_1606_p2;
reg   [5:0] add_ln52_71_reg_5295;
wire   [0:0] icmp_ln52_144_fu_1622_p2;
reg   [0:0] icmp_ln52_144_reg_5301;
wire   [0:0] icmp_ln51_72_fu_1628_p2;
reg   [0:0] icmp_ln51_72_reg_5306;
wire   [5:0] add_ln52_72_fu_1692_p2;
reg   [5:0] add_ln52_72_reg_5311;
wire   [0:0] icmp_ln52_146_fu_1708_p2;
reg   [0:0] icmp_ln52_146_reg_5317;
wire   [0:0] icmp_ln51_73_fu_1714_p2;
reg   [0:0] icmp_ln51_73_reg_5322;
wire   [5:0] add_ln52_73_fu_1778_p2;
reg   [5:0] add_ln52_73_reg_5327;
wire   [0:0] icmp_ln52_148_fu_1794_p2;
reg   [0:0] icmp_ln52_148_reg_5333;
wire   [0:0] icmp_ln51_74_fu_1800_p2;
reg   [0:0] icmp_ln51_74_reg_5338;
wire   [5:0] add_ln52_74_fu_1864_p2;
reg   [5:0] add_ln52_74_reg_5343;
wire   [0:0] icmp_ln52_150_fu_1880_p2;
reg   [0:0] icmp_ln52_150_reg_5349;
wire   [0:0] icmp_ln51_75_fu_1886_p2;
reg   [0:0] icmp_ln51_75_reg_5354;
wire   [5:0] add_ln52_75_fu_1950_p2;
reg   [5:0] add_ln52_75_reg_5359;
wire   [0:0] icmp_ln52_152_fu_1966_p2;
reg   [0:0] icmp_ln52_152_reg_5365;
wire   [0:0] icmp_ln51_76_fu_1972_p2;
reg   [0:0] icmp_ln51_76_reg_5370;
wire   [5:0] add_ln52_76_fu_2036_p2;
reg   [5:0] add_ln52_76_reg_5375;
wire   [0:0] icmp_ln52_154_fu_2052_p2;
reg   [0:0] icmp_ln52_154_reg_5381;
wire   [0:0] icmp_ln51_77_fu_2058_p2;
reg   [0:0] icmp_ln51_77_reg_5386;
wire   [5:0] add_ln52_77_fu_2122_p2;
reg   [5:0] add_ln52_77_reg_5391;
wire   [0:0] icmp_ln52_156_fu_2138_p2;
reg   [0:0] icmp_ln52_156_reg_5397;
wire   [0:0] icmp_ln51_78_fu_2144_p2;
reg   [0:0] icmp_ln51_78_reg_5402;
wire   [5:0] add_ln52_78_fu_2208_p2;
reg   [5:0] add_ln52_78_reg_5407;
wire   [0:0] icmp_ln52_158_fu_2224_p2;
reg   [0:0] icmp_ln52_158_reg_5413;
wire   [0:0] icmp_ln51_79_fu_2230_p2;
reg   [0:0] icmp_ln51_79_reg_5418;
wire   [5:0] add_ln52_79_fu_2294_p2;
reg   [5:0] add_ln52_79_reg_5423;
wire   [0:0] icmp_ln52_160_fu_2310_p2;
reg   [0:0] icmp_ln52_160_reg_5429;
wire   [0:0] icmp_ln51_80_fu_2316_p2;
reg   [0:0] icmp_ln51_80_reg_5434;
wire   [5:0] add_ln52_80_fu_2380_p2;
reg   [5:0] add_ln52_80_reg_5439;
wire   [0:0] icmp_ln52_162_fu_2396_p2;
reg   [0:0] icmp_ln52_162_reg_5445;
wire   [0:0] icmp_ln51_81_fu_2402_p2;
reg   [0:0] icmp_ln51_81_reg_5450;
wire   [5:0] add_ln52_81_fu_2466_p2;
reg   [5:0] add_ln52_81_reg_5455;
wire   [0:0] icmp_ln52_164_fu_2482_p2;
reg   [0:0] icmp_ln52_164_reg_5461;
wire   [0:0] icmp_ln51_82_fu_2488_p2;
reg   [0:0] icmp_ln51_82_reg_5466;
wire   [5:0] add_ln52_82_fu_2552_p2;
reg   [5:0] add_ln52_82_reg_5471;
wire   [0:0] icmp_ln52_166_fu_2568_p2;
reg   [0:0] icmp_ln52_166_reg_5477;
wire   [0:0] icmp_ln51_83_fu_2574_p2;
reg   [0:0] icmp_ln51_83_reg_5482;
wire   [5:0] add_ln52_83_fu_2638_p2;
reg   [5:0] add_ln52_83_reg_5487;
wire   [0:0] icmp_ln52_168_fu_2654_p2;
reg   [0:0] icmp_ln52_168_reg_5493;
wire   [0:0] icmp_ln51_84_fu_2660_p2;
reg   [0:0] icmp_ln51_84_reg_5498;
wire   [5:0] add_ln52_84_fu_2724_p2;
reg   [5:0] add_ln52_84_reg_5503;
wire   [0:0] icmp_ln52_170_fu_2740_p2;
reg   [0:0] icmp_ln52_170_reg_5509;
wire   [0:0] icmp_ln51_85_fu_2746_p2;
reg   [0:0] icmp_ln51_85_reg_5514;
wire   [5:0] add_ln52_85_fu_2810_p2;
reg   [5:0] add_ln52_85_reg_5519;
wire   [0:0] icmp_ln52_172_fu_2826_p2;
reg   [0:0] icmp_ln52_172_reg_5525;
wire   [0:0] icmp_ln51_86_fu_2832_p2;
reg   [0:0] icmp_ln51_86_reg_5530;
wire   [5:0] add_ln52_86_fu_2896_p2;
reg   [5:0] add_ln52_86_reg_5535;
wire   [0:0] icmp_ln52_174_fu_2912_p2;
reg   [0:0] icmp_ln52_174_reg_5541;
wire   [0:0] icmp_ln51_87_fu_2918_p2;
reg   [0:0] icmp_ln51_87_reg_5546;
wire   [5:0] add_ln52_87_fu_2982_p2;
reg   [5:0] add_ln52_87_reg_5551;
wire   [0:0] icmp_ln52_176_fu_2998_p2;
reg   [0:0] icmp_ln52_176_reg_5557;
wire   [0:0] icmp_ln51_88_fu_3004_p2;
reg   [0:0] icmp_ln51_88_reg_5562;
wire   [5:0] add_ln52_88_fu_3068_p2;
reg   [5:0] add_ln52_88_reg_5567;
wire   [0:0] icmp_ln52_178_fu_3084_p2;
reg   [0:0] icmp_ln52_178_reg_5573;
wire   [0:0] icmp_ln51_89_fu_3090_p2;
reg   [0:0] icmp_ln51_89_reg_5578;
wire   [5:0] add_ln52_89_fu_3154_p2;
reg   [5:0] add_ln52_89_reg_5583;
wire   [0:0] icmp_ln52_180_fu_3170_p2;
reg   [0:0] icmp_ln52_180_reg_5589;
wire   [0:0] icmp_ln51_90_fu_3176_p2;
reg   [0:0] icmp_ln51_90_reg_5594;
wire   [5:0] add_ln52_90_fu_3240_p2;
reg   [5:0] add_ln52_90_reg_5599;
wire   [0:0] icmp_ln52_182_fu_3256_p2;
reg   [0:0] icmp_ln52_182_reg_5605;
wire   [0:0] icmp_ln51_91_fu_3262_p2;
reg   [0:0] icmp_ln51_91_reg_5610;
wire   [5:0] add_ln52_91_fu_3326_p2;
reg   [5:0] add_ln52_91_reg_5615;
wire   [0:0] icmp_ln52_184_fu_3342_p2;
reg   [0:0] icmp_ln52_184_reg_5621;
wire   [0:0] icmp_ln51_92_fu_3348_p2;
reg   [0:0] icmp_ln51_92_reg_5626;
wire   [5:0] add_ln52_92_fu_3412_p2;
reg   [5:0] add_ln52_92_reg_5631;
wire   [0:0] icmp_ln52_186_fu_3428_p2;
reg   [0:0] icmp_ln52_186_reg_5637;
wire   [0:0] icmp_ln51_93_fu_3434_p2;
reg   [0:0] icmp_ln51_93_reg_5642;
wire   [5:0] add_ln52_93_fu_3498_p2;
reg   [5:0] add_ln52_93_reg_5647;
wire   [0:0] icmp_ln52_188_fu_3514_p2;
reg   [0:0] icmp_ln52_188_reg_5653;
wire   [0:0] icmp_ln51_94_fu_3520_p2;
reg   [0:0] icmp_ln51_94_reg_5658;
wire   [5:0] add_ln52_94_fu_3584_p2;
reg   [5:0] add_ln52_94_reg_5663;
wire   [0:0] icmp_ln52_190_fu_3600_p2;
reg   [0:0] icmp_ln52_190_reg_5669;
reg   [5:0] i_fu_504;
wire   [5:0] i_12_fu_535_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_11;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] trunc_ln44_fu_546_p1;
wire   [3:0] trunc_ln52_fu_892_p1;
wire   [0:0] tmp_fu_876_p3;
wire   [0:0] icmp_ln52_fu_896_p2;
wire   [0:0] or_ln52_fu_902_p2;
wire   [0:0] tmp_383_fu_884_p3;
wire   [0:0] and_ln52_fu_908_p2;
wire   [5:0] trunc_ln4_fu_866_p4;
wire   [5:0] zext_ln52_fu_914_p1;
wire   [10:0] tmp_s_fu_924_p4;
wire   [21:0] trunc_ln44_64_fu_570_p4;
wire   [3:0] tmp_127_fu_972_p4;
wire   [0:0] tmp_386_fu_956_p3;
wire   [0:0] icmp_ln52_129_fu_982_p2;
wire   [0:0] or_ln52_126_fu_988_p2;
wire   [0:0] tmp_387_fu_964_p3;
wire   [0:0] and_ln52_129_fu_994_p2;
wire   [5:0] trunc_ln52_s_fu_946_p4;
wire   [5:0] zext_ln52_64_fu_1000_p1;
wire   [10:0] tmp_128_fu_1010_p4;
wire   [21:0] trunc_ln44_65_fu_580_p4;
wire   [3:0] tmp_129_fu_1058_p4;
wire   [0:0] tmp_390_fu_1042_p3;
wire   [0:0] icmp_ln52_131_fu_1068_p2;
wire   [0:0] or_ln52_127_fu_1074_p2;
wire   [0:0] tmp_391_fu_1050_p3;
wire   [0:0] and_ln52_131_fu_1080_p2;
wire   [5:0] trunc_ln52_63_fu_1032_p4;
wire   [5:0] zext_ln52_65_fu_1086_p1;
wire   [10:0] tmp_130_fu_1096_p4;
wire   [21:0] trunc_ln44_66_fu_590_p4;
wire   [3:0] tmp_131_fu_1144_p4;
wire   [0:0] tmp_394_fu_1128_p3;
wire   [0:0] icmp_ln52_133_fu_1154_p2;
wire   [0:0] or_ln52_128_fu_1160_p2;
wire   [0:0] tmp_395_fu_1136_p3;
wire   [0:0] and_ln52_133_fu_1166_p2;
wire   [5:0] trunc_ln52_64_fu_1118_p4;
wire   [5:0] zext_ln52_66_fu_1172_p1;
wire   [10:0] tmp_132_fu_1182_p4;
wire   [21:0] trunc_ln44_67_fu_600_p4;
wire   [3:0] tmp_133_fu_1230_p4;
wire   [0:0] tmp_398_fu_1214_p3;
wire   [0:0] icmp_ln52_135_fu_1240_p2;
wire   [0:0] or_ln52_129_fu_1246_p2;
wire   [0:0] tmp_399_fu_1222_p3;
wire   [0:0] and_ln52_135_fu_1252_p2;
wire   [5:0] trunc_ln52_65_fu_1204_p4;
wire   [5:0] zext_ln52_67_fu_1258_p1;
wire   [10:0] tmp_134_fu_1268_p4;
wire   [21:0] trunc_ln44_68_fu_610_p4;
wire   [3:0] tmp_135_fu_1316_p4;
wire   [0:0] tmp_402_fu_1300_p3;
wire   [0:0] icmp_ln52_137_fu_1326_p2;
wire   [0:0] or_ln52_130_fu_1332_p2;
wire   [0:0] tmp_403_fu_1308_p3;
wire   [0:0] and_ln52_137_fu_1338_p2;
wire   [5:0] trunc_ln52_66_fu_1290_p4;
wire   [5:0] zext_ln52_68_fu_1344_p1;
wire   [10:0] tmp_136_fu_1354_p4;
wire   [21:0] trunc_ln44_69_fu_620_p4;
wire   [3:0] tmp_137_fu_1402_p4;
wire   [0:0] tmp_406_fu_1386_p3;
wire   [0:0] icmp_ln52_139_fu_1412_p2;
wire   [0:0] or_ln52_131_fu_1418_p2;
wire   [0:0] tmp_407_fu_1394_p3;
wire   [0:0] and_ln52_139_fu_1424_p2;
wire   [5:0] trunc_ln52_67_fu_1376_p4;
wire   [5:0] zext_ln52_69_fu_1430_p1;
wire   [10:0] tmp_138_fu_1440_p4;
wire   [21:0] trunc_ln44_70_fu_630_p4;
wire   [3:0] tmp_139_fu_1488_p4;
wire   [0:0] tmp_410_fu_1472_p3;
wire   [0:0] icmp_ln52_141_fu_1498_p2;
wire   [0:0] or_ln52_132_fu_1504_p2;
wire   [0:0] tmp_411_fu_1480_p3;
wire   [0:0] and_ln52_141_fu_1510_p2;
wire   [5:0] trunc_ln52_68_fu_1462_p4;
wire   [5:0] zext_ln52_70_fu_1516_p1;
wire   [10:0] tmp_140_fu_1526_p4;
wire   [21:0] trunc_ln44_71_fu_640_p4;
wire   [3:0] tmp_141_fu_1574_p4;
wire   [0:0] tmp_414_fu_1558_p3;
wire   [0:0] icmp_ln52_143_fu_1584_p2;
wire   [0:0] or_ln52_133_fu_1590_p2;
wire   [0:0] tmp_415_fu_1566_p3;
wire   [0:0] and_ln52_143_fu_1596_p2;
wire   [5:0] trunc_ln52_69_fu_1548_p4;
wire   [5:0] zext_ln52_71_fu_1602_p1;
wire   [10:0] tmp_142_fu_1612_p4;
wire   [21:0] trunc_ln44_72_fu_650_p4;
wire   [3:0] tmp_143_fu_1660_p4;
wire   [0:0] tmp_418_fu_1644_p3;
wire   [0:0] icmp_ln52_145_fu_1670_p2;
wire   [0:0] or_ln52_134_fu_1676_p2;
wire   [0:0] tmp_419_fu_1652_p3;
wire   [0:0] and_ln52_145_fu_1682_p2;
wire   [5:0] trunc_ln52_70_fu_1634_p4;
wire   [5:0] zext_ln52_72_fu_1688_p1;
wire   [10:0] tmp_144_fu_1698_p4;
wire   [21:0] trunc_ln44_73_fu_660_p4;
wire   [3:0] tmp_145_fu_1746_p4;
wire   [0:0] tmp_422_fu_1730_p3;
wire   [0:0] icmp_ln52_147_fu_1756_p2;
wire   [0:0] or_ln52_135_fu_1762_p2;
wire   [0:0] tmp_423_fu_1738_p3;
wire   [0:0] and_ln52_147_fu_1768_p2;
wire   [5:0] trunc_ln52_71_fu_1720_p4;
wire   [5:0] zext_ln52_73_fu_1774_p1;
wire   [10:0] tmp_146_fu_1784_p4;
wire   [21:0] trunc_ln44_74_fu_670_p4;
wire   [3:0] tmp_147_fu_1832_p4;
wire   [0:0] tmp_426_fu_1816_p3;
wire   [0:0] icmp_ln52_149_fu_1842_p2;
wire   [0:0] or_ln52_136_fu_1848_p2;
wire   [0:0] tmp_427_fu_1824_p3;
wire   [0:0] and_ln52_149_fu_1854_p2;
wire   [5:0] trunc_ln52_72_fu_1806_p4;
wire   [5:0] zext_ln52_74_fu_1860_p1;
wire   [10:0] tmp_148_fu_1870_p4;
wire   [21:0] trunc_ln44_75_fu_680_p4;
wire   [3:0] tmp_149_fu_1918_p4;
wire   [0:0] tmp_430_fu_1902_p3;
wire   [0:0] icmp_ln52_151_fu_1928_p2;
wire   [0:0] or_ln52_137_fu_1934_p2;
wire   [0:0] tmp_431_fu_1910_p3;
wire   [0:0] and_ln52_151_fu_1940_p2;
wire   [5:0] trunc_ln52_73_fu_1892_p4;
wire   [5:0] zext_ln52_75_fu_1946_p1;
wire   [10:0] tmp_150_fu_1956_p4;
wire   [21:0] trunc_ln44_76_fu_690_p4;
wire   [3:0] tmp_151_fu_2004_p4;
wire   [0:0] tmp_434_fu_1988_p3;
wire   [0:0] icmp_ln52_153_fu_2014_p2;
wire   [0:0] or_ln52_138_fu_2020_p2;
wire   [0:0] tmp_435_fu_1996_p3;
wire   [0:0] and_ln52_153_fu_2026_p2;
wire   [5:0] trunc_ln52_74_fu_1978_p4;
wire   [5:0] zext_ln52_76_fu_2032_p1;
wire   [10:0] tmp_152_fu_2042_p4;
wire   [21:0] trunc_ln44_77_fu_700_p4;
wire   [3:0] tmp_153_fu_2090_p4;
wire   [0:0] tmp_438_fu_2074_p3;
wire   [0:0] icmp_ln52_155_fu_2100_p2;
wire   [0:0] or_ln52_139_fu_2106_p2;
wire   [0:0] tmp_439_fu_2082_p3;
wire   [0:0] and_ln52_155_fu_2112_p2;
wire   [5:0] trunc_ln52_75_fu_2064_p4;
wire   [5:0] zext_ln52_77_fu_2118_p1;
wire   [10:0] tmp_154_fu_2128_p4;
wire   [21:0] trunc_ln44_78_fu_710_p4;
wire   [3:0] tmp_155_fu_2176_p4;
wire   [0:0] tmp_442_fu_2160_p3;
wire   [0:0] icmp_ln52_157_fu_2186_p2;
wire   [0:0] or_ln52_140_fu_2192_p2;
wire   [0:0] tmp_443_fu_2168_p3;
wire   [0:0] and_ln52_157_fu_2198_p2;
wire   [5:0] trunc_ln52_76_fu_2150_p4;
wire   [5:0] zext_ln52_78_fu_2204_p1;
wire   [10:0] tmp_156_fu_2214_p4;
wire   [21:0] trunc_ln44_79_fu_720_p4;
wire   [3:0] tmp_157_fu_2262_p4;
wire   [0:0] tmp_446_fu_2246_p3;
wire   [0:0] icmp_ln52_159_fu_2272_p2;
wire   [0:0] or_ln52_141_fu_2278_p2;
wire   [0:0] tmp_447_fu_2254_p3;
wire   [0:0] and_ln52_159_fu_2284_p2;
wire   [5:0] trunc_ln52_77_fu_2236_p4;
wire   [5:0] zext_ln52_79_fu_2290_p1;
wire   [10:0] tmp_158_fu_2300_p4;
wire   [21:0] trunc_ln44_80_fu_730_p4;
wire   [3:0] tmp_159_fu_2348_p4;
wire   [0:0] tmp_450_fu_2332_p3;
wire   [0:0] icmp_ln52_161_fu_2358_p2;
wire   [0:0] or_ln52_142_fu_2364_p2;
wire   [0:0] tmp_451_fu_2340_p3;
wire   [0:0] and_ln52_161_fu_2370_p2;
wire   [5:0] trunc_ln52_78_fu_2322_p4;
wire   [5:0] zext_ln52_80_fu_2376_p1;
wire   [10:0] tmp_160_fu_2386_p4;
wire   [21:0] trunc_ln44_81_fu_740_p4;
wire   [3:0] tmp_161_fu_2434_p4;
wire   [0:0] tmp_454_fu_2418_p3;
wire   [0:0] icmp_ln52_163_fu_2444_p2;
wire   [0:0] or_ln52_143_fu_2450_p2;
wire   [0:0] tmp_455_fu_2426_p3;
wire   [0:0] and_ln52_163_fu_2456_p2;
wire   [5:0] trunc_ln52_79_fu_2408_p4;
wire   [5:0] zext_ln52_81_fu_2462_p1;
wire   [10:0] tmp_162_fu_2472_p4;
wire   [21:0] trunc_ln44_82_fu_750_p4;
wire   [3:0] tmp_163_fu_2520_p4;
wire   [0:0] tmp_458_fu_2504_p3;
wire   [0:0] icmp_ln52_165_fu_2530_p2;
wire   [0:0] or_ln52_144_fu_2536_p2;
wire   [0:0] tmp_459_fu_2512_p3;
wire   [0:0] and_ln52_165_fu_2542_p2;
wire   [5:0] trunc_ln52_80_fu_2494_p4;
wire   [5:0] zext_ln52_82_fu_2548_p1;
wire   [10:0] tmp_164_fu_2558_p4;
wire   [21:0] trunc_ln44_83_fu_760_p4;
wire   [3:0] tmp_165_fu_2606_p4;
wire   [0:0] tmp_462_fu_2590_p3;
wire   [0:0] icmp_ln52_167_fu_2616_p2;
wire   [0:0] or_ln52_145_fu_2622_p2;
wire   [0:0] tmp_463_fu_2598_p3;
wire   [0:0] and_ln52_167_fu_2628_p2;
wire   [5:0] trunc_ln52_81_fu_2580_p4;
wire   [5:0] zext_ln52_83_fu_2634_p1;
wire   [10:0] tmp_166_fu_2644_p4;
wire   [21:0] trunc_ln44_84_fu_770_p4;
wire   [3:0] tmp_167_fu_2692_p4;
wire   [0:0] tmp_466_fu_2676_p3;
wire   [0:0] icmp_ln52_169_fu_2702_p2;
wire   [0:0] or_ln52_146_fu_2708_p2;
wire   [0:0] tmp_467_fu_2684_p3;
wire   [0:0] and_ln52_169_fu_2714_p2;
wire   [5:0] trunc_ln52_82_fu_2666_p4;
wire   [5:0] zext_ln52_84_fu_2720_p1;
wire   [10:0] tmp_168_fu_2730_p4;
wire   [21:0] trunc_ln44_85_fu_780_p4;
wire   [3:0] tmp_169_fu_2778_p4;
wire   [0:0] tmp_470_fu_2762_p3;
wire   [0:0] icmp_ln52_171_fu_2788_p2;
wire   [0:0] or_ln52_147_fu_2794_p2;
wire   [0:0] tmp_471_fu_2770_p3;
wire   [0:0] and_ln52_171_fu_2800_p2;
wire   [5:0] trunc_ln52_83_fu_2752_p4;
wire   [5:0] zext_ln52_85_fu_2806_p1;
wire   [10:0] tmp_170_fu_2816_p4;
wire   [21:0] trunc_ln44_86_fu_790_p4;
wire   [3:0] tmp_171_fu_2864_p4;
wire   [0:0] tmp_474_fu_2848_p3;
wire   [0:0] icmp_ln52_173_fu_2874_p2;
wire   [0:0] or_ln52_148_fu_2880_p2;
wire   [0:0] tmp_475_fu_2856_p3;
wire   [0:0] and_ln52_173_fu_2886_p2;
wire   [5:0] trunc_ln52_84_fu_2838_p4;
wire   [5:0] zext_ln52_86_fu_2892_p1;
wire   [10:0] tmp_172_fu_2902_p4;
wire   [21:0] trunc_ln44_87_fu_800_p4;
wire   [3:0] tmp_173_fu_2950_p4;
wire   [0:0] tmp_478_fu_2934_p3;
wire   [0:0] icmp_ln52_175_fu_2960_p2;
wire   [0:0] or_ln52_149_fu_2966_p2;
wire   [0:0] tmp_479_fu_2942_p3;
wire   [0:0] and_ln52_175_fu_2972_p2;
wire   [5:0] trunc_ln52_85_fu_2924_p4;
wire   [5:0] zext_ln52_87_fu_2978_p1;
wire   [10:0] tmp_174_fu_2988_p4;
wire   [21:0] trunc_ln44_88_fu_810_p4;
wire   [3:0] tmp_175_fu_3036_p4;
wire   [0:0] tmp_482_fu_3020_p3;
wire   [0:0] icmp_ln52_177_fu_3046_p2;
wire   [0:0] or_ln52_150_fu_3052_p2;
wire   [0:0] tmp_483_fu_3028_p3;
wire   [0:0] and_ln52_177_fu_3058_p2;
wire   [5:0] trunc_ln52_86_fu_3010_p4;
wire   [5:0] zext_ln52_88_fu_3064_p1;
wire   [10:0] tmp_176_fu_3074_p4;
wire   [21:0] trunc_ln44_89_fu_820_p4;
wire   [3:0] tmp_177_fu_3122_p4;
wire   [0:0] tmp_486_fu_3106_p3;
wire   [0:0] icmp_ln52_179_fu_3132_p2;
wire   [0:0] or_ln52_151_fu_3138_p2;
wire   [0:0] tmp_487_fu_3114_p3;
wire   [0:0] and_ln52_179_fu_3144_p2;
wire   [5:0] trunc_ln52_87_fu_3096_p4;
wire   [5:0] zext_ln52_89_fu_3150_p1;
wire   [10:0] tmp_178_fu_3160_p4;
wire   [21:0] trunc_ln44_90_fu_830_p4;
wire   [3:0] tmp_179_fu_3208_p4;
wire   [0:0] tmp_490_fu_3192_p3;
wire   [0:0] icmp_ln52_181_fu_3218_p2;
wire   [0:0] or_ln52_152_fu_3224_p2;
wire   [0:0] tmp_491_fu_3200_p3;
wire   [0:0] and_ln52_181_fu_3230_p2;
wire   [5:0] trunc_ln52_88_fu_3182_p4;
wire   [5:0] zext_ln52_90_fu_3236_p1;
wire   [10:0] tmp_180_fu_3246_p4;
wire   [21:0] trunc_ln44_91_fu_840_p4;
wire   [3:0] tmp_181_fu_3294_p4;
wire   [0:0] tmp_494_fu_3278_p3;
wire   [0:0] icmp_ln52_183_fu_3304_p2;
wire   [0:0] or_ln52_153_fu_3310_p2;
wire   [0:0] tmp_495_fu_3286_p3;
wire   [0:0] and_ln52_183_fu_3316_p2;
wire   [5:0] trunc_ln52_89_fu_3268_p4;
wire   [5:0] zext_ln52_91_fu_3322_p1;
wire   [10:0] tmp_182_fu_3332_p4;
wire   [21:0] trunc_ln44_92_fu_850_p4;
wire   [3:0] tmp_183_fu_3380_p4;
wire   [0:0] tmp_498_fu_3364_p3;
wire   [0:0] icmp_ln52_185_fu_3390_p2;
wire   [0:0] or_ln52_154_fu_3396_p2;
wire   [0:0] tmp_499_fu_3372_p3;
wire   [0:0] and_ln52_185_fu_3402_p2;
wire   [5:0] trunc_ln52_90_fu_3354_p4;
wire   [5:0] zext_ln52_92_fu_3408_p1;
wire   [10:0] tmp_184_fu_3418_p4;
wire   [21:0] trunc_ln44_s_fu_550_p4;
wire   [3:0] tmp_185_fu_3466_p4;
wire   [0:0] tmp_502_fu_3450_p3;
wire   [0:0] icmp_ln52_187_fu_3476_p2;
wire   [0:0] or_ln52_155_fu_3482_p2;
wire   [0:0] tmp_503_fu_3458_p3;
wire   [0:0] and_ln52_187_fu_3488_p2;
wire   [5:0] trunc_ln52_91_fu_3440_p4;
wire   [5:0] zext_ln52_93_fu_3494_p1;
wire   [10:0] tmp_186_fu_3504_p4;
wire   [21:0] trunc_ln44_63_fu_560_p4;
wire   [3:0] tmp_187_fu_3552_p4;
wire   [0:0] tmp_506_fu_3536_p3;
wire   [0:0] icmp_ln52_189_fu_3562_p2;
wire   [0:0] or_ln52_156_fu_3568_p2;
wire   [0:0] tmp_507_fu_3544_p3;
wire   [0:0] and_ln52_189_fu_3574_p2;
wire   [5:0] trunc_ln52_92_fu_3526_p4;
wire   [5:0] zext_ln52_94_fu_3580_p1;
wire   [10:0] tmp_188_fu_3590_p4;
wire   [0:0] tmp_385_fu_3613_p3;
wire   [0:0] tmp_384_fu_3606_p3;
wire   [0:0] xor_ln52_fu_3620_p2;
wire   [0:0] or_ln52_157_fu_3626_p2;
wire   [0:0] and_ln52_128_fu_3632_p2;
wire   [5:0] out_data_fu_3637_p3;
wire   [0:0] tmp_389_fu_3658_p3;
wire   [0:0] tmp_388_fu_3651_p3;
wire   [0:0] xor_ln52_64_fu_3665_p2;
wire   [0:0] or_ln52_158_fu_3671_p2;
wire   [0:0] and_ln52_130_fu_3677_p2;
wire   [5:0] out_data_17_fu_3682_p3;
wire   [0:0] tmp_393_fu_3703_p3;
wire   [0:0] tmp_392_fu_3696_p3;
wire   [0:0] xor_ln52_65_fu_3710_p2;
wire   [0:0] or_ln52_159_fu_3716_p2;
wire   [0:0] and_ln52_132_fu_3722_p2;
wire   [5:0] out_data_19_fu_3727_p3;
wire   [0:0] tmp_397_fu_3748_p3;
wire   [0:0] tmp_396_fu_3741_p3;
wire   [0:0] xor_ln52_66_fu_3755_p2;
wire   [0:0] or_ln52_160_fu_3761_p2;
wire   [0:0] and_ln52_134_fu_3767_p2;
wire   [5:0] out_data_21_fu_3772_p3;
wire   [0:0] tmp_401_fu_3793_p3;
wire   [0:0] tmp_400_fu_3786_p3;
wire   [0:0] xor_ln52_67_fu_3800_p2;
wire   [0:0] or_ln52_161_fu_3806_p2;
wire   [0:0] and_ln52_136_fu_3812_p2;
wire   [5:0] out_data_23_fu_3817_p3;
wire   [0:0] tmp_405_fu_3838_p3;
wire   [0:0] tmp_404_fu_3831_p3;
wire   [0:0] xor_ln52_68_fu_3845_p2;
wire   [0:0] or_ln52_162_fu_3851_p2;
wire   [0:0] and_ln52_138_fu_3857_p2;
wire   [5:0] out_data_25_fu_3862_p3;
wire   [0:0] tmp_409_fu_3883_p3;
wire   [0:0] tmp_408_fu_3876_p3;
wire   [0:0] xor_ln52_69_fu_3890_p2;
wire   [0:0] or_ln52_163_fu_3896_p2;
wire   [0:0] and_ln52_140_fu_3902_p2;
wire   [5:0] out_data_27_fu_3907_p3;
wire   [0:0] tmp_413_fu_3928_p3;
wire   [0:0] tmp_412_fu_3921_p3;
wire   [0:0] xor_ln52_70_fu_3935_p2;
wire   [0:0] or_ln52_164_fu_3941_p2;
wire   [0:0] and_ln52_142_fu_3947_p2;
wire   [5:0] out_data_29_fu_3952_p3;
wire   [0:0] tmp_417_fu_3973_p3;
wire   [0:0] tmp_416_fu_3966_p3;
wire   [0:0] xor_ln52_71_fu_3980_p2;
wire   [0:0] or_ln52_165_fu_3986_p2;
wire   [0:0] and_ln52_144_fu_3992_p2;
wire   [5:0] select_ln52_fu_3997_p3;
wire   [0:0] tmp_421_fu_4018_p3;
wire   [0:0] tmp_420_fu_4011_p3;
wire   [0:0] xor_ln52_72_fu_4025_p2;
wire   [0:0] or_ln52_166_fu_4031_p2;
wire   [0:0] and_ln52_146_fu_4037_p2;
wire   [5:0] select_ln52_72_fu_4042_p3;
wire   [0:0] tmp_425_fu_4063_p3;
wire   [0:0] tmp_424_fu_4056_p3;
wire   [0:0] xor_ln52_73_fu_4070_p2;
wire   [0:0] or_ln52_167_fu_4076_p2;
wire   [0:0] and_ln52_148_fu_4082_p2;
wire   [5:0] select_ln52_73_fu_4087_p3;
wire   [0:0] tmp_429_fu_4108_p3;
wire   [0:0] tmp_428_fu_4101_p3;
wire   [0:0] xor_ln52_74_fu_4115_p2;
wire   [0:0] or_ln52_168_fu_4121_p2;
wire   [0:0] and_ln52_150_fu_4127_p2;
wire   [5:0] select_ln52_74_fu_4132_p3;
wire   [0:0] tmp_433_fu_4153_p3;
wire   [0:0] tmp_432_fu_4146_p3;
wire   [0:0] xor_ln52_75_fu_4160_p2;
wire   [0:0] or_ln52_169_fu_4166_p2;
wire   [0:0] and_ln52_152_fu_4172_p2;
wire   [5:0] select_ln52_75_fu_4177_p3;
wire   [0:0] tmp_437_fu_4198_p3;
wire   [0:0] tmp_436_fu_4191_p3;
wire   [0:0] xor_ln52_76_fu_4205_p2;
wire   [0:0] or_ln52_170_fu_4211_p2;
wire   [0:0] and_ln52_154_fu_4217_p2;
wire   [5:0] select_ln52_76_fu_4222_p3;
wire   [0:0] tmp_441_fu_4243_p3;
wire   [0:0] tmp_440_fu_4236_p3;
wire   [0:0] xor_ln52_77_fu_4250_p2;
wire   [0:0] or_ln52_171_fu_4256_p2;
wire   [0:0] and_ln52_156_fu_4262_p2;
wire   [5:0] select_ln52_77_fu_4267_p3;
wire   [0:0] tmp_445_fu_4288_p3;
wire   [0:0] tmp_444_fu_4281_p3;
wire   [0:0] xor_ln52_78_fu_4295_p2;
wire   [0:0] or_ln52_172_fu_4301_p2;
wire   [0:0] and_ln52_158_fu_4307_p2;
wire   [5:0] select_ln52_78_fu_4312_p3;
wire   [0:0] tmp_449_fu_4333_p3;
wire   [0:0] tmp_448_fu_4326_p3;
wire   [0:0] xor_ln52_79_fu_4340_p2;
wire   [0:0] or_ln52_173_fu_4346_p2;
wire   [0:0] and_ln52_160_fu_4352_p2;
wire   [5:0] select_ln52_79_fu_4357_p3;
wire   [0:0] tmp_453_fu_4378_p3;
wire   [0:0] tmp_452_fu_4371_p3;
wire   [0:0] xor_ln52_80_fu_4385_p2;
wire   [0:0] or_ln52_174_fu_4391_p2;
wire   [0:0] and_ln52_162_fu_4397_p2;
wire   [5:0] select_ln52_80_fu_4402_p3;
wire   [0:0] tmp_457_fu_4423_p3;
wire   [0:0] tmp_456_fu_4416_p3;
wire   [0:0] xor_ln52_81_fu_4430_p2;
wire   [0:0] or_ln52_175_fu_4436_p2;
wire   [0:0] and_ln52_164_fu_4442_p2;
wire   [5:0] select_ln52_81_fu_4447_p3;
wire   [0:0] tmp_461_fu_4468_p3;
wire   [0:0] tmp_460_fu_4461_p3;
wire   [0:0] xor_ln52_82_fu_4475_p2;
wire   [0:0] or_ln52_176_fu_4481_p2;
wire   [0:0] and_ln52_166_fu_4487_p2;
wire   [5:0] select_ln52_82_fu_4492_p3;
wire   [0:0] tmp_465_fu_4513_p3;
wire   [0:0] tmp_464_fu_4506_p3;
wire   [0:0] xor_ln52_83_fu_4520_p2;
wire   [0:0] or_ln52_177_fu_4526_p2;
wire   [0:0] and_ln52_168_fu_4532_p2;
wire   [5:0] select_ln52_83_fu_4537_p3;
wire   [0:0] tmp_469_fu_4558_p3;
wire   [0:0] tmp_468_fu_4551_p3;
wire   [0:0] xor_ln52_84_fu_4565_p2;
wire   [0:0] or_ln52_178_fu_4571_p2;
wire   [0:0] and_ln52_170_fu_4577_p2;
wire   [5:0] select_ln52_84_fu_4582_p3;
wire   [0:0] tmp_473_fu_4603_p3;
wire   [0:0] tmp_472_fu_4596_p3;
wire   [0:0] xor_ln52_85_fu_4610_p2;
wire   [0:0] or_ln52_179_fu_4616_p2;
wire   [0:0] and_ln52_172_fu_4622_p2;
wire   [5:0] select_ln52_85_fu_4627_p3;
wire   [0:0] tmp_477_fu_4648_p3;
wire   [0:0] tmp_476_fu_4641_p3;
wire   [0:0] xor_ln52_86_fu_4655_p2;
wire   [0:0] or_ln52_180_fu_4661_p2;
wire   [0:0] and_ln52_174_fu_4667_p2;
wire   [5:0] select_ln52_86_fu_4672_p3;
wire   [0:0] tmp_481_fu_4693_p3;
wire   [0:0] tmp_480_fu_4686_p3;
wire   [0:0] xor_ln52_87_fu_4700_p2;
wire   [0:0] or_ln52_181_fu_4706_p2;
wire   [0:0] and_ln52_176_fu_4712_p2;
wire   [5:0] select_ln52_87_fu_4717_p3;
wire   [0:0] tmp_485_fu_4738_p3;
wire   [0:0] tmp_484_fu_4731_p3;
wire   [0:0] xor_ln52_88_fu_4745_p2;
wire   [0:0] or_ln52_182_fu_4751_p2;
wire   [0:0] and_ln52_178_fu_4757_p2;
wire   [5:0] select_ln52_88_fu_4762_p3;
wire   [0:0] tmp_489_fu_4783_p3;
wire   [0:0] tmp_488_fu_4776_p3;
wire   [0:0] xor_ln52_89_fu_4790_p2;
wire   [0:0] or_ln52_183_fu_4796_p2;
wire   [0:0] and_ln52_180_fu_4802_p2;
wire   [5:0] select_ln52_89_fu_4807_p3;
wire   [0:0] tmp_493_fu_4828_p3;
wire   [0:0] tmp_492_fu_4821_p3;
wire   [0:0] xor_ln52_90_fu_4835_p2;
wire   [0:0] or_ln52_184_fu_4841_p2;
wire   [0:0] and_ln52_182_fu_4847_p2;
wire   [5:0] select_ln52_90_fu_4852_p3;
wire   [0:0] tmp_497_fu_4873_p3;
wire   [0:0] tmp_496_fu_4866_p3;
wire   [0:0] xor_ln52_91_fu_4880_p2;
wire   [0:0] or_ln52_185_fu_4886_p2;
wire   [0:0] and_ln52_184_fu_4892_p2;
wire   [5:0] select_ln52_91_fu_4897_p3;
wire   [0:0] tmp_501_fu_4918_p3;
wire   [0:0] tmp_500_fu_4911_p3;
wire   [0:0] xor_ln52_92_fu_4925_p2;
wire   [0:0] or_ln52_186_fu_4931_p2;
wire   [0:0] and_ln52_186_fu_4937_p2;
wire   [5:0] select_ln52_92_fu_4942_p3;
wire   [0:0] tmp_505_fu_4963_p3;
wire   [0:0] tmp_504_fu_4956_p3;
wire   [0:0] xor_ln52_93_fu_4970_p2;
wire   [0:0] or_ln52_187_fu_4976_p2;
wire   [0:0] and_ln52_188_fu_4982_p2;
wire   [5:0] select_ln52_93_fu_4987_p3;
wire   [0:0] tmp_509_fu_5008_p3;
wire   [0:0] tmp_508_fu_5001_p3;
wire   [0:0] xor_ln52_94_fu_5015_p2;
wire   [0:0] or_ln52_188_fu_5021_p2;
wire   [0:0] and_ln52_190_fu_5027_p2;
wire   [5:0] select_ln52_94_fu_5032_p3;
wire   [5:0] select_ln51_94_fu_5039_p3;
wire   [5:0] select_ln51_93_fu_4994_p3;
wire   [5:0] select_ln51_92_fu_4949_p3;
wire   [5:0] select_ln51_91_fu_4904_p3;
wire   [5:0] select_ln51_90_fu_4859_p3;
wire   [5:0] select_ln51_89_fu_4814_p3;
wire   [5:0] select_ln51_88_fu_4769_p3;
wire   [5:0] select_ln51_87_fu_4724_p3;
wire   [5:0] select_ln51_86_fu_4679_p3;
wire   [5:0] select_ln51_85_fu_4634_p3;
wire   [5:0] select_ln51_84_fu_4589_p3;
wire   [5:0] select_ln51_83_fu_4544_p3;
wire   [5:0] select_ln51_82_fu_4499_p3;
wire   [5:0] select_ln51_81_fu_4454_p3;
wire   [5:0] select_ln51_80_fu_4409_p3;
wire   [5:0] select_ln51_79_fu_4364_p3;
wire   [5:0] select_ln51_78_fu_4319_p3;
wire   [5:0] select_ln51_77_fu_4274_p3;
wire   [5:0] select_ln51_76_fu_4229_p3;
wire   [5:0] select_ln51_75_fu_4184_p3;
wire   [5:0] select_ln51_74_fu_4139_p3;
wire   [5:0] select_ln51_73_fu_4094_p3;
wire   [5:0] select_ln51_72_fu_4049_p3;
wire   [5:0] select_ln51_fu_4004_p3;
wire   [5:0] out_data_30_fu_3959_p3;
wire   [5:0] out_data_28_fu_3914_p3;
wire   [5:0] out_data_26_fu_3869_p3;
wire   [5:0] out_data_24_fu_3824_p3;
wire   [5:0] out_data_22_fu_3779_p3;
wire   [5:0] out_data_20_fu_3734_p3;
wire   [5:0] out_data_18_fu_3689_p3;
wire   [5:0] out_data_16_fu_3644_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_304;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_304)) begin
        if ((icmp_ln41_fu_529_p2 == 1'd0)) begin
            i_fu_504 <= i_12_fu_535_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_504 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln52_64_reg_5183 <= add_ln52_64_fu_1004_p2;
        add_ln52_65_reg_5199 <= add_ln52_65_fu_1090_p2;
        add_ln52_66_reg_5215 <= add_ln52_66_fu_1176_p2;
        add_ln52_67_reg_5231 <= add_ln52_67_fu_1262_p2;
        add_ln52_68_reg_5247 <= add_ln52_68_fu_1348_p2;
        add_ln52_69_reg_5263 <= add_ln52_69_fu_1434_p2;
        add_ln52_70_reg_5279 <= add_ln52_70_fu_1520_p2;
        add_ln52_71_reg_5295 <= add_ln52_71_fu_1606_p2;
        add_ln52_72_reg_5311 <= add_ln52_72_fu_1692_p2;
        add_ln52_73_reg_5327 <= add_ln52_73_fu_1778_p2;
        add_ln52_74_reg_5343 <= add_ln52_74_fu_1864_p2;
        add_ln52_75_reg_5359 <= add_ln52_75_fu_1950_p2;
        add_ln52_76_reg_5375 <= add_ln52_76_fu_2036_p2;
        add_ln52_77_reg_5391 <= add_ln52_77_fu_2122_p2;
        add_ln52_78_reg_5407 <= add_ln52_78_fu_2208_p2;
        add_ln52_79_reg_5423 <= add_ln52_79_fu_2294_p2;
        add_ln52_80_reg_5439 <= add_ln52_80_fu_2380_p2;
        add_ln52_81_reg_5455 <= add_ln52_81_fu_2466_p2;
        add_ln52_82_reg_5471 <= add_ln52_82_fu_2552_p2;
        add_ln52_83_reg_5487 <= add_ln52_83_fu_2638_p2;
        add_ln52_84_reg_5503 <= add_ln52_84_fu_2724_p2;
        add_ln52_85_reg_5519 <= add_ln52_85_fu_2810_p2;
        add_ln52_86_reg_5535 <= add_ln52_86_fu_2896_p2;
        add_ln52_87_reg_5551 <= add_ln52_87_fu_2982_p2;
        add_ln52_88_reg_5567 <= add_ln52_88_fu_3068_p2;
        add_ln52_89_reg_5583 <= add_ln52_89_fu_3154_p2;
        add_ln52_90_reg_5599 <= add_ln52_90_fu_3240_p2;
        add_ln52_91_reg_5615 <= add_ln52_91_fu_3326_p2;
        add_ln52_92_reg_5631 <= add_ln52_92_fu_3412_p2;
        add_ln52_93_reg_5647 <= add_ln52_93_fu_3498_p2;
        add_ln52_94_reg_5663 <= add_ln52_94_fu_3584_p2;
        add_ln52_reg_5167 <= add_ln52_fu_918_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln51_64_reg_5178 <= icmp_ln51_64_fu_940_p2;
        icmp_ln51_65_reg_5194 <= icmp_ln51_65_fu_1026_p2;
        icmp_ln51_66_reg_5210 <= icmp_ln51_66_fu_1112_p2;
        icmp_ln51_67_reg_5226 <= icmp_ln51_67_fu_1198_p2;
        icmp_ln51_68_reg_5242 <= icmp_ln51_68_fu_1284_p2;
        icmp_ln51_69_reg_5258 <= icmp_ln51_69_fu_1370_p2;
        icmp_ln51_70_reg_5274 <= icmp_ln51_70_fu_1456_p2;
        icmp_ln51_71_reg_5290 <= icmp_ln51_71_fu_1542_p2;
        icmp_ln51_72_reg_5306 <= icmp_ln51_72_fu_1628_p2;
        icmp_ln51_73_reg_5322 <= icmp_ln51_73_fu_1714_p2;
        icmp_ln51_74_reg_5338 <= icmp_ln51_74_fu_1800_p2;
        icmp_ln51_75_reg_5354 <= icmp_ln51_75_fu_1886_p2;
        icmp_ln51_76_reg_5370 <= icmp_ln51_76_fu_1972_p2;
        icmp_ln51_77_reg_5386 <= icmp_ln51_77_fu_2058_p2;
        icmp_ln51_78_reg_5402 <= icmp_ln51_78_fu_2144_p2;
        icmp_ln51_79_reg_5418 <= icmp_ln51_79_fu_2230_p2;
        icmp_ln51_80_reg_5434 <= icmp_ln51_80_fu_2316_p2;
        icmp_ln51_81_reg_5450 <= icmp_ln51_81_fu_2402_p2;
        icmp_ln51_82_reg_5466 <= icmp_ln51_82_fu_2488_p2;
        icmp_ln51_83_reg_5482 <= icmp_ln51_83_fu_2574_p2;
        icmp_ln51_84_reg_5498 <= icmp_ln51_84_fu_2660_p2;
        icmp_ln51_85_reg_5514 <= icmp_ln51_85_fu_2746_p2;
        icmp_ln51_86_reg_5530 <= icmp_ln51_86_fu_2832_p2;
        icmp_ln51_87_reg_5546 <= icmp_ln51_87_fu_2918_p2;
        icmp_ln51_88_reg_5562 <= icmp_ln51_88_fu_3004_p2;
        icmp_ln51_89_reg_5578 <= icmp_ln51_89_fu_3090_p2;
        icmp_ln51_90_reg_5594 <= icmp_ln51_90_fu_3176_p2;
        icmp_ln51_91_reg_5610 <= icmp_ln51_91_fu_3262_p2;
        icmp_ln51_92_reg_5626 <= icmp_ln51_92_fu_3348_p2;
        icmp_ln51_93_reg_5642 <= icmp_ln51_93_fu_3434_p2;
        icmp_ln51_94_reg_5658 <= icmp_ln51_94_fu_3520_p2;
        icmp_ln51_reg_5162 <= icmp_ln51_fu_860_p2;
        icmp_ln52_128_reg_5173 <= icmp_ln52_128_fu_934_p2;
        icmp_ln52_130_reg_5189 <= icmp_ln52_130_fu_1020_p2;
        icmp_ln52_132_reg_5205 <= icmp_ln52_132_fu_1106_p2;
        icmp_ln52_134_reg_5221 <= icmp_ln52_134_fu_1192_p2;
        icmp_ln52_136_reg_5237 <= icmp_ln52_136_fu_1278_p2;
        icmp_ln52_138_reg_5253 <= icmp_ln52_138_fu_1364_p2;
        icmp_ln52_140_reg_5269 <= icmp_ln52_140_fu_1450_p2;
        icmp_ln52_142_reg_5285 <= icmp_ln52_142_fu_1536_p2;
        icmp_ln52_144_reg_5301 <= icmp_ln52_144_fu_1622_p2;
        icmp_ln52_146_reg_5317 <= icmp_ln52_146_fu_1708_p2;
        icmp_ln52_148_reg_5333 <= icmp_ln52_148_fu_1794_p2;
        icmp_ln52_150_reg_5349 <= icmp_ln52_150_fu_1880_p2;
        icmp_ln52_152_reg_5365 <= icmp_ln52_152_fu_1966_p2;
        icmp_ln52_154_reg_5381 <= icmp_ln52_154_fu_2052_p2;
        icmp_ln52_156_reg_5397 <= icmp_ln52_156_fu_2138_p2;
        icmp_ln52_158_reg_5413 <= icmp_ln52_158_fu_2224_p2;
        icmp_ln52_160_reg_5429 <= icmp_ln52_160_fu_2310_p2;
        icmp_ln52_162_reg_5445 <= icmp_ln52_162_fu_2396_p2;
        icmp_ln52_164_reg_5461 <= icmp_ln52_164_fu_2482_p2;
        icmp_ln52_166_reg_5477 <= icmp_ln52_166_fu_2568_p2;
        icmp_ln52_168_reg_5493 <= icmp_ln52_168_fu_2654_p2;
        icmp_ln52_170_reg_5509 <= icmp_ln52_170_fu_2740_p2;
        icmp_ln52_172_reg_5525 <= icmp_ln52_172_fu_2826_p2;
        icmp_ln52_174_reg_5541 <= icmp_ln52_174_fu_2912_p2;
        icmp_ln52_176_reg_5557 <= icmp_ln52_176_fu_2998_p2;
        icmp_ln52_178_reg_5573 <= icmp_ln52_178_fu_3084_p2;
        icmp_ln52_180_reg_5589 <= icmp_ln52_180_fu_3170_p2;
        icmp_ln52_182_reg_5605 <= icmp_ln52_182_fu_3256_p2;
        icmp_ln52_184_reg_5621 <= icmp_ln52_184_fu_3342_p2;
        icmp_ln52_186_reg_5637 <= icmp_ln52_186_fu_3428_p2;
        icmp_ln52_188_reg_5653 <= icmp_ln52_188_fu_3514_p2;
        icmp_ln52_190_reg_5669 <= icmp_ln52_190_fu_3600_p2;
        layer5_out_read_reg_5126 <= layer5_out_dout;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_529_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_11 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_11 = i_fu_504;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer7_out_write = 1'b1;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_64_fu_1004_p2 = (trunc_ln52_s_fu_946_p4 + zext_ln52_64_fu_1000_p1);

assign add_ln52_65_fu_1090_p2 = (trunc_ln52_63_fu_1032_p4 + zext_ln52_65_fu_1086_p1);

assign add_ln52_66_fu_1176_p2 = (trunc_ln52_64_fu_1118_p4 + zext_ln52_66_fu_1172_p1);

assign add_ln52_67_fu_1262_p2 = (trunc_ln52_65_fu_1204_p4 + zext_ln52_67_fu_1258_p1);

assign add_ln52_68_fu_1348_p2 = (trunc_ln52_66_fu_1290_p4 + zext_ln52_68_fu_1344_p1);

assign add_ln52_69_fu_1434_p2 = (trunc_ln52_67_fu_1376_p4 + zext_ln52_69_fu_1430_p1);

assign add_ln52_70_fu_1520_p2 = (trunc_ln52_68_fu_1462_p4 + zext_ln52_70_fu_1516_p1);

assign add_ln52_71_fu_1606_p2 = (trunc_ln52_69_fu_1548_p4 + zext_ln52_71_fu_1602_p1);

assign add_ln52_72_fu_1692_p2 = (trunc_ln52_70_fu_1634_p4 + zext_ln52_72_fu_1688_p1);

assign add_ln52_73_fu_1778_p2 = (trunc_ln52_71_fu_1720_p4 + zext_ln52_73_fu_1774_p1);

assign add_ln52_74_fu_1864_p2 = (trunc_ln52_72_fu_1806_p4 + zext_ln52_74_fu_1860_p1);

assign add_ln52_75_fu_1950_p2 = (trunc_ln52_73_fu_1892_p4 + zext_ln52_75_fu_1946_p1);

assign add_ln52_76_fu_2036_p2 = (trunc_ln52_74_fu_1978_p4 + zext_ln52_76_fu_2032_p1);

assign add_ln52_77_fu_2122_p2 = (trunc_ln52_75_fu_2064_p4 + zext_ln52_77_fu_2118_p1);

assign add_ln52_78_fu_2208_p2 = (trunc_ln52_76_fu_2150_p4 + zext_ln52_78_fu_2204_p1);

assign add_ln52_79_fu_2294_p2 = (trunc_ln52_77_fu_2236_p4 + zext_ln52_79_fu_2290_p1);

assign add_ln52_80_fu_2380_p2 = (trunc_ln52_78_fu_2322_p4 + zext_ln52_80_fu_2376_p1);

assign add_ln52_81_fu_2466_p2 = (trunc_ln52_79_fu_2408_p4 + zext_ln52_81_fu_2462_p1);

assign add_ln52_82_fu_2552_p2 = (trunc_ln52_80_fu_2494_p4 + zext_ln52_82_fu_2548_p1);

assign add_ln52_83_fu_2638_p2 = (trunc_ln52_81_fu_2580_p4 + zext_ln52_83_fu_2634_p1);

assign add_ln52_84_fu_2724_p2 = (trunc_ln52_82_fu_2666_p4 + zext_ln52_84_fu_2720_p1);

assign add_ln52_85_fu_2810_p2 = (trunc_ln52_83_fu_2752_p4 + zext_ln52_85_fu_2806_p1);

assign add_ln52_86_fu_2896_p2 = (trunc_ln52_84_fu_2838_p4 + zext_ln52_86_fu_2892_p1);

assign add_ln52_87_fu_2982_p2 = (trunc_ln52_85_fu_2924_p4 + zext_ln52_87_fu_2978_p1);

assign add_ln52_88_fu_3068_p2 = (trunc_ln52_86_fu_3010_p4 + zext_ln52_88_fu_3064_p1);

assign add_ln52_89_fu_3154_p2 = (trunc_ln52_87_fu_3096_p4 + zext_ln52_89_fu_3150_p1);

assign add_ln52_90_fu_3240_p2 = (trunc_ln52_88_fu_3182_p4 + zext_ln52_90_fu_3236_p1);

assign add_ln52_91_fu_3326_p2 = (trunc_ln52_89_fu_3268_p4 + zext_ln52_91_fu_3322_p1);

assign add_ln52_92_fu_3412_p2 = (trunc_ln52_90_fu_3354_p4 + zext_ln52_92_fu_3408_p1);

assign add_ln52_93_fu_3498_p2 = (trunc_ln52_91_fu_3440_p4 + zext_ln52_93_fu_3494_p1);

assign add_ln52_94_fu_3584_p2 = (trunc_ln52_92_fu_3526_p4 + zext_ln52_94_fu_3580_p1);

assign add_ln52_fu_918_p2 = (trunc_ln4_fu_866_p4 + zext_ln52_fu_914_p1);

assign and_ln52_128_fu_3632_p2 = (or_ln52_157_fu_3626_p2 & icmp_ln52_128_reg_5173);

assign and_ln52_129_fu_994_p2 = (tmp_387_fu_964_p3 & or_ln52_126_fu_988_p2);

assign and_ln52_130_fu_3677_p2 = (or_ln52_158_fu_3671_p2 & icmp_ln52_130_reg_5189);

assign and_ln52_131_fu_1080_p2 = (tmp_391_fu_1050_p3 & or_ln52_127_fu_1074_p2);

assign and_ln52_132_fu_3722_p2 = (or_ln52_159_fu_3716_p2 & icmp_ln52_132_reg_5205);

assign and_ln52_133_fu_1166_p2 = (tmp_395_fu_1136_p3 & or_ln52_128_fu_1160_p2);

assign and_ln52_134_fu_3767_p2 = (or_ln52_160_fu_3761_p2 & icmp_ln52_134_reg_5221);

assign and_ln52_135_fu_1252_p2 = (tmp_399_fu_1222_p3 & or_ln52_129_fu_1246_p2);

assign and_ln52_136_fu_3812_p2 = (or_ln52_161_fu_3806_p2 & icmp_ln52_136_reg_5237);

assign and_ln52_137_fu_1338_p2 = (tmp_403_fu_1308_p3 & or_ln52_130_fu_1332_p2);

assign and_ln52_138_fu_3857_p2 = (or_ln52_162_fu_3851_p2 & icmp_ln52_138_reg_5253);

assign and_ln52_139_fu_1424_p2 = (tmp_407_fu_1394_p3 & or_ln52_131_fu_1418_p2);

assign and_ln52_140_fu_3902_p2 = (or_ln52_163_fu_3896_p2 & icmp_ln52_140_reg_5269);

assign and_ln52_141_fu_1510_p2 = (tmp_411_fu_1480_p3 & or_ln52_132_fu_1504_p2);

assign and_ln52_142_fu_3947_p2 = (or_ln52_164_fu_3941_p2 & icmp_ln52_142_reg_5285);

assign and_ln52_143_fu_1596_p2 = (tmp_415_fu_1566_p3 & or_ln52_133_fu_1590_p2);

assign and_ln52_144_fu_3992_p2 = (or_ln52_165_fu_3986_p2 & icmp_ln52_144_reg_5301);

assign and_ln52_145_fu_1682_p2 = (tmp_419_fu_1652_p3 & or_ln52_134_fu_1676_p2);

assign and_ln52_146_fu_4037_p2 = (or_ln52_166_fu_4031_p2 & icmp_ln52_146_reg_5317);

assign and_ln52_147_fu_1768_p2 = (tmp_423_fu_1738_p3 & or_ln52_135_fu_1762_p2);

assign and_ln52_148_fu_4082_p2 = (or_ln52_167_fu_4076_p2 & icmp_ln52_148_reg_5333);

assign and_ln52_149_fu_1854_p2 = (tmp_427_fu_1824_p3 & or_ln52_136_fu_1848_p2);

assign and_ln52_150_fu_4127_p2 = (or_ln52_168_fu_4121_p2 & icmp_ln52_150_reg_5349);

assign and_ln52_151_fu_1940_p2 = (tmp_431_fu_1910_p3 & or_ln52_137_fu_1934_p2);

assign and_ln52_152_fu_4172_p2 = (or_ln52_169_fu_4166_p2 & icmp_ln52_152_reg_5365);

assign and_ln52_153_fu_2026_p2 = (tmp_435_fu_1996_p3 & or_ln52_138_fu_2020_p2);

assign and_ln52_154_fu_4217_p2 = (or_ln52_170_fu_4211_p2 & icmp_ln52_154_reg_5381);

assign and_ln52_155_fu_2112_p2 = (tmp_439_fu_2082_p3 & or_ln52_139_fu_2106_p2);

assign and_ln52_156_fu_4262_p2 = (or_ln52_171_fu_4256_p2 & icmp_ln52_156_reg_5397);

assign and_ln52_157_fu_2198_p2 = (tmp_443_fu_2168_p3 & or_ln52_140_fu_2192_p2);

assign and_ln52_158_fu_4307_p2 = (or_ln52_172_fu_4301_p2 & icmp_ln52_158_reg_5413);

assign and_ln52_159_fu_2284_p2 = (tmp_447_fu_2254_p3 & or_ln52_141_fu_2278_p2);

assign and_ln52_160_fu_4352_p2 = (or_ln52_173_fu_4346_p2 & icmp_ln52_160_reg_5429);

assign and_ln52_161_fu_2370_p2 = (tmp_451_fu_2340_p3 & or_ln52_142_fu_2364_p2);

assign and_ln52_162_fu_4397_p2 = (or_ln52_174_fu_4391_p2 & icmp_ln52_162_reg_5445);

assign and_ln52_163_fu_2456_p2 = (tmp_455_fu_2426_p3 & or_ln52_143_fu_2450_p2);

assign and_ln52_164_fu_4442_p2 = (or_ln52_175_fu_4436_p2 & icmp_ln52_164_reg_5461);

assign and_ln52_165_fu_2542_p2 = (tmp_459_fu_2512_p3 & or_ln52_144_fu_2536_p2);

assign and_ln52_166_fu_4487_p2 = (or_ln52_176_fu_4481_p2 & icmp_ln52_166_reg_5477);

assign and_ln52_167_fu_2628_p2 = (tmp_463_fu_2598_p3 & or_ln52_145_fu_2622_p2);

assign and_ln52_168_fu_4532_p2 = (or_ln52_177_fu_4526_p2 & icmp_ln52_168_reg_5493);

assign and_ln52_169_fu_2714_p2 = (tmp_467_fu_2684_p3 & or_ln52_146_fu_2708_p2);

assign and_ln52_170_fu_4577_p2 = (or_ln52_178_fu_4571_p2 & icmp_ln52_170_reg_5509);

assign and_ln52_171_fu_2800_p2 = (tmp_471_fu_2770_p3 & or_ln52_147_fu_2794_p2);

assign and_ln52_172_fu_4622_p2 = (or_ln52_179_fu_4616_p2 & icmp_ln52_172_reg_5525);

assign and_ln52_173_fu_2886_p2 = (tmp_475_fu_2856_p3 & or_ln52_148_fu_2880_p2);

assign and_ln52_174_fu_4667_p2 = (or_ln52_180_fu_4661_p2 & icmp_ln52_174_reg_5541);

assign and_ln52_175_fu_2972_p2 = (tmp_479_fu_2942_p3 & or_ln52_149_fu_2966_p2);

assign and_ln52_176_fu_4712_p2 = (or_ln52_181_fu_4706_p2 & icmp_ln52_176_reg_5557);

assign and_ln52_177_fu_3058_p2 = (tmp_483_fu_3028_p3 & or_ln52_150_fu_3052_p2);

assign and_ln52_178_fu_4757_p2 = (or_ln52_182_fu_4751_p2 & icmp_ln52_178_reg_5573);

assign and_ln52_179_fu_3144_p2 = (tmp_487_fu_3114_p3 & or_ln52_151_fu_3138_p2);

assign and_ln52_180_fu_4802_p2 = (or_ln52_183_fu_4796_p2 & icmp_ln52_180_reg_5589);

assign and_ln52_181_fu_3230_p2 = (tmp_491_fu_3200_p3 & or_ln52_152_fu_3224_p2);

assign and_ln52_182_fu_4847_p2 = (or_ln52_184_fu_4841_p2 & icmp_ln52_182_reg_5605);

assign and_ln52_183_fu_3316_p2 = (tmp_495_fu_3286_p3 & or_ln52_153_fu_3310_p2);

assign and_ln52_184_fu_4892_p2 = (or_ln52_185_fu_4886_p2 & icmp_ln52_184_reg_5621);

assign and_ln52_185_fu_3402_p2 = (tmp_499_fu_3372_p3 & or_ln52_154_fu_3396_p2);

assign and_ln52_186_fu_4937_p2 = (or_ln52_186_fu_4931_p2 & icmp_ln52_186_reg_5637);

assign and_ln52_187_fu_3488_p2 = (tmp_503_fu_3458_p3 & or_ln52_155_fu_3482_p2);

assign and_ln52_188_fu_4982_p2 = (or_ln52_187_fu_4976_p2 & icmp_ln52_188_reg_5653);

assign and_ln52_189_fu_3574_p2 = (tmp_507_fu_3544_p3 & or_ln52_156_fu_3568_p2);

assign and_ln52_190_fu_5027_p2 = (or_ln52_188_fu_5021_p2 & icmp_ln52_190_reg_5669);

assign and_ln52_fu_908_p2 = (tmp_383_fu_884_p3 & or_ln52_fu_902_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer5_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer7_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_304 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_12_fu_535_p2 = (ap_sig_allocacmp_i_11 + 6'd1);

assign icmp_ln41_fu_529_p2 = ((ap_sig_allocacmp_i_11 == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln51_64_fu_940_p2 = (($signed(trunc_ln44_64_fu_570_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_65_fu_1026_p2 = (($signed(trunc_ln44_65_fu_580_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_66_fu_1112_p2 = (($signed(trunc_ln44_66_fu_590_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_67_fu_1198_p2 = (($signed(trunc_ln44_67_fu_600_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_68_fu_1284_p2 = (($signed(trunc_ln44_68_fu_610_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_69_fu_1370_p2 = (($signed(trunc_ln44_69_fu_620_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_70_fu_1456_p2 = (($signed(trunc_ln44_70_fu_630_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_71_fu_1542_p2 = (($signed(trunc_ln44_71_fu_640_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_72_fu_1628_p2 = (($signed(trunc_ln44_72_fu_650_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_73_fu_1714_p2 = (($signed(trunc_ln44_73_fu_660_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_74_fu_1800_p2 = (($signed(trunc_ln44_74_fu_670_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_75_fu_1886_p2 = (($signed(trunc_ln44_75_fu_680_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_76_fu_1972_p2 = (($signed(trunc_ln44_76_fu_690_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_77_fu_2058_p2 = (($signed(trunc_ln44_77_fu_700_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_78_fu_2144_p2 = (($signed(trunc_ln44_78_fu_710_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_79_fu_2230_p2 = (($signed(trunc_ln44_79_fu_720_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_80_fu_2316_p2 = (($signed(trunc_ln44_80_fu_730_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_81_fu_2402_p2 = (($signed(trunc_ln44_81_fu_740_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_82_fu_2488_p2 = (($signed(trunc_ln44_82_fu_750_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_83_fu_2574_p2 = (($signed(trunc_ln44_83_fu_760_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_84_fu_2660_p2 = (($signed(trunc_ln44_84_fu_770_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_85_fu_2746_p2 = (($signed(trunc_ln44_85_fu_780_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_86_fu_2832_p2 = (($signed(trunc_ln44_86_fu_790_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_87_fu_2918_p2 = (($signed(trunc_ln44_87_fu_800_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_88_fu_3004_p2 = (($signed(trunc_ln44_88_fu_810_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_89_fu_3090_p2 = (($signed(trunc_ln44_89_fu_820_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_90_fu_3176_p2 = (($signed(trunc_ln44_90_fu_830_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_91_fu_3262_p2 = (($signed(trunc_ln44_91_fu_840_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_92_fu_3348_p2 = (($signed(trunc_ln44_92_fu_850_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_93_fu_3434_p2 = (($signed(trunc_ln44_s_fu_550_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_94_fu_3520_p2 = (($signed(trunc_ln44_63_fu_560_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_860_p2 = (($signed(trunc_ln44_fu_546_p1) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_128_fu_934_p2 = ((tmp_s_fu_924_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_129_fu_982_p2 = ((tmp_127_fu_972_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_130_fu_1020_p2 = ((tmp_128_fu_1010_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_131_fu_1068_p2 = ((tmp_129_fu_1058_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_132_fu_1106_p2 = ((tmp_130_fu_1096_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_133_fu_1154_p2 = ((tmp_131_fu_1144_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_134_fu_1192_p2 = ((tmp_132_fu_1182_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_135_fu_1240_p2 = ((tmp_133_fu_1230_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_136_fu_1278_p2 = ((tmp_134_fu_1268_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_137_fu_1326_p2 = ((tmp_135_fu_1316_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_138_fu_1364_p2 = ((tmp_136_fu_1354_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_139_fu_1412_p2 = ((tmp_137_fu_1402_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_140_fu_1450_p2 = ((tmp_138_fu_1440_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_141_fu_1498_p2 = ((tmp_139_fu_1488_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_142_fu_1536_p2 = ((tmp_140_fu_1526_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_143_fu_1584_p2 = ((tmp_141_fu_1574_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_144_fu_1622_p2 = ((tmp_142_fu_1612_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_145_fu_1670_p2 = ((tmp_143_fu_1660_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_146_fu_1708_p2 = ((tmp_144_fu_1698_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_147_fu_1756_p2 = ((tmp_145_fu_1746_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_148_fu_1794_p2 = ((tmp_146_fu_1784_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_149_fu_1842_p2 = ((tmp_147_fu_1832_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_150_fu_1880_p2 = ((tmp_148_fu_1870_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_151_fu_1928_p2 = ((tmp_149_fu_1918_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_152_fu_1966_p2 = ((tmp_150_fu_1956_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_153_fu_2014_p2 = ((tmp_151_fu_2004_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_154_fu_2052_p2 = ((tmp_152_fu_2042_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_155_fu_2100_p2 = ((tmp_153_fu_2090_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_156_fu_2138_p2 = ((tmp_154_fu_2128_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_157_fu_2186_p2 = ((tmp_155_fu_2176_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_158_fu_2224_p2 = ((tmp_156_fu_2214_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_159_fu_2272_p2 = ((tmp_157_fu_2262_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_160_fu_2310_p2 = ((tmp_158_fu_2300_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_161_fu_2358_p2 = ((tmp_159_fu_2348_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_162_fu_2396_p2 = ((tmp_160_fu_2386_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_163_fu_2444_p2 = ((tmp_161_fu_2434_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_164_fu_2482_p2 = ((tmp_162_fu_2472_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_165_fu_2530_p2 = ((tmp_163_fu_2520_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_166_fu_2568_p2 = ((tmp_164_fu_2558_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_167_fu_2616_p2 = ((tmp_165_fu_2606_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_168_fu_2654_p2 = ((tmp_166_fu_2644_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_169_fu_2702_p2 = ((tmp_167_fu_2692_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_170_fu_2740_p2 = ((tmp_168_fu_2730_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_171_fu_2788_p2 = ((tmp_169_fu_2778_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_172_fu_2826_p2 = ((tmp_170_fu_2816_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_173_fu_2874_p2 = ((tmp_171_fu_2864_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_174_fu_2912_p2 = ((tmp_172_fu_2902_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_175_fu_2960_p2 = ((tmp_173_fu_2950_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_176_fu_2998_p2 = ((tmp_174_fu_2988_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_177_fu_3046_p2 = ((tmp_175_fu_3036_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_178_fu_3084_p2 = ((tmp_176_fu_3074_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_179_fu_3132_p2 = ((tmp_177_fu_3122_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_180_fu_3170_p2 = ((tmp_178_fu_3160_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_181_fu_3218_p2 = ((tmp_179_fu_3208_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_182_fu_3256_p2 = ((tmp_180_fu_3246_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_183_fu_3304_p2 = ((tmp_181_fu_3294_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_184_fu_3342_p2 = ((tmp_182_fu_3332_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_185_fu_3390_p2 = ((tmp_183_fu_3380_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_186_fu_3428_p2 = ((tmp_184_fu_3418_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_187_fu_3476_p2 = ((tmp_185_fu_3466_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_188_fu_3514_p2 = ((tmp_186_fu_3504_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_189_fu_3562_p2 = ((tmp_187_fu_3552_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_190_fu_3600_p2 = ((tmp_188_fu_3590_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_896_p2 = ((trunc_ln52_fu_892_p1 != 4'd0) ? 1'b1 : 1'b0);

assign layer7_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_94_fu_5039_p3}, {select_ln51_93_fu_4994_p3}}, {select_ln51_92_fu_4949_p3}}, {select_ln51_91_fu_4904_p3}}, {select_ln51_90_fu_4859_p3}}, {select_ln51_89_fu_4814_p3}}, {select_ln51_88_fu_4769_p3}}, {select_ln51_87_fu_4724_p3}}, {select_ln51_86_fu_4679_p3}}, {select_ln51_85_fu_4634_p3}}, {select_ln51_84_fu_4589_p3}}, {select_ln51_83_fu_4544_p3}}, {select_ln51_82_fu_4499_p3}}, {select_ln51_81_fu_4454_p3}}, {select_ln51_80_fu_4409_p3}}, {select_ln51_79_fu_4364_p3}}, {select_ln51_78_fu_4319_p3}}, {select_ln51_77_fu_4274_p3}}, {select_ln51_76_fu_4229_p3}}, {select_ln51_75_fu_4184_p3}}, {select_ln51_74_fu_4139_p3}}, {select_ln51_73_fu_4094_p3}}, {select_ln51_72_fu_4049_p3}}, {select_ln51_fu_4004_p3}}, {out_data_30_fu_3959_p3}}, {out_data_28_fu_3914_p3}}, {out_data_26_fu_3869_p3}}, {out_data_24_fu_3824_p3}}, {out_data_22_fu_3779_p3}}, {out_data_20_fu_3734_p3}}, {out_data_18_fu_3689_p3}}, {out_data_16_fu_3644_p3}};

assign or_ln52_126_fu_988_p2 = (tmp_386_fu_956_p3 | icmp_ln52_129_fu_982_p2);

assign or_ln52_127_fu_1074_p2 = (tmp_390_fu_1042_p3 | icmp_ln52_131_fu_1068_p2);

assign or_ln52_128_fu_1160_p2 = (tmp_394_fu_1128_p3 | icmp_ln52_133_fu_1154_p2);

assign or_ln52_129_fu_1246_p2 = (tmp_398_fu_1214_p3 | icmp_ln52_135_fu_1240_p2);

assign or_ln52_130_fu_1332_p2 = (tmp_402_fu_1300_p3 | icmp_ln52_137_fu_1326_p2);

assign or_ln52_131_fu_1418_p2 = (tmp_406_fu_1386_p3 | icmp_ln52_139_fu_1412_p2);

assign or_ln52_132_fu_1504_p2 = (tmp_410_fu_1472_p3 | icmp_ln52_141_fu_1498_p2);

assign or_ln52_133_fu_1590_p2 = (tmp_414_fu_1558_p3 | icmp_ln52_143_fu_1584_p2);

assign or_ln52_134_fu_1676_p2 = (tmp_418_fu_1644_p3 | icmp_ln52_145_fu_1670_p2);

assign or_ln52_135_fu_1762_p2 = (tmp_422_fu_1730_p3 | icmp_ln52_147_fu_1756_p2);

assign or_ln52_136_fu_1848_p2 = (tmp_426_fu_1816_p3 | icmp_ln52_149_fu_1842_p2);

assign or_ln52_137_fu_1934_p2 = (tmp_430_fu_1902_p3 | icmp_ln52_151_fu_1928_p2);

assign or_ln52_138_fu_2020_p2 = (tmp_434_fu_1988_p3 | icmp_ln52_153_fu_2014_p2);

assign or_ln52_139_fu_2106_p2 = (tmp_438_fu_2074_p3 | icmp_ln52_155_fu_2100_p2);

assign or_ln52_140_fu_2192_p2 = (tmp_442_fu_2160_p3 | icmp_ln52_157_fu_2186_p2);

assign or_ln52_141_fu_2278_p2 = (tmp_446_fu_2246_p3 | icmp_ln52_159_fu_2272_p2);

assign or_ln52_142_fu_2364_p2 = (tmp_450_fu_2332_p3 | icmp_ln52_161_fu_2358_p2);

assign or_ln52_143_fu_2450_p2 = (tmp_454_fu_2418_p3 | icmp_ln52_163_fu_2444_p2);

assign or_ln52_144_fu_2536_p2 = (tmp_458_fu_2504_p3 | icmp_ln52_165_fu_2530_p2);

assign or_ln52_145_fu_2622_p2 = (tmp_462_fu_2590_p3 | icmp_ln52_167_fu_2616_p2);

assign or_ln52_146_fu_2708_p2 = (tmp_466_fu_2676_p3 | icmp_ln52_169_fu_2702_p2);

assign or_ln52_147_fu_2794_p2 = (tmp_470_fu_2762_p3 | icmp_ln52_171_fu_2788_p2);

assign or_ln52_148_fu_2880_p2 = (tmp_474_fu_2848_p3 | icmp_ln52_173_fu_2874_p2);

assign or_ln52_149_fu_2966_p2 = (tmp_478_fu_2934_p3 | icmp_ln52_175_fu_2960_p2);

assign or_ln52_150_fu_3052_p2 = (tmp_482_fu_3020_p3 | icmp_ln52_177_fu_3046_p2);

assign or_ln52_151_fu_3138_p2 = (tmp_486_fu_3106_p3 | icmp_ln52_179_fu_3132_p2);

assign or_ln52_152_fu_3224_p2 = (tmp_490_fu_3192_p3 | icmp_ln52_181_fu_3218_p2);

assign or_ln52_153_fu_3310_p2 = (tmp_494_fu_3278_p3 | icmp_ln52_183_fu_3304_p2);

assign or_ln52_154_fu_3396_p2 = (tmp_498_fu_3364_p3 | icmp_ln52_185_fu_3390_p2);

assign or_ln52_155_fu_3482_p2 = (tmp_502_fu_3450_p3 | icmp_ln52_187_fu_3476_p2);

assign or_ln52_156_fu_3568_p2 = (tmp_506_fu_3536_p3 | icmp_ln52_189_fu_3562_p2);

assign or_ln52_157_fu_3626_p2 = (xor_ln52_fu_3620_p2 | tmp_384_fu_3606_p3);

assign or_ln52_158_fu_3671_p2 = (xor_ln52_64_fu_3665_p2 | tmp_388_fu_3651_p3);

assign or_ln52_159_fu_3716_p2 = (xor_ln52_65_fu_3710_p2 | tmp_392_fu_3696_p3);

assign or_ln52_160_fu_3761_p2 = (xor_ln52_66_fu_3755_p2 | tmp_396_fu_3741_p3);

assign or_ln52_161_fu_3806_p2 = (xor_ln52_67_fu_3800_p2 | tmp_400_fu_3786_p3);

assign or_ln52_162_fu_3851_p2 = (xor_ln52_68_fu_3845_p2 | tmp_404_fu_3831_p3);

assign or_ln52_163_fu_3896_p2 = (xor_ln52_69_fu_3890_p2 | tmp_408_fu_3876_p3);

assign or_ln52_164_fu_3941_p2 = (xor_ln52_70_fu_3935_p2 | tmp_412_fu_3921_p3);

assign or_ln52_165_fu_3986_p2 = (xor_ln52_71_fu_3980_p2 | tmp_416_fu_3966_p3);

assign or_ln52_166_fu_4031_p2 = (xor_ln52_72_fu_4025_p2 | tmp_420_fu_4011_p3);

assign or_ln52_167_fu_4076_p2 = (xor_ln52_73_fu_4070_p2 | tmp_424_fu_4056_p3);

assign or_ln52_168_fu_4121_p2 = (xor_ln52_74_fu_4115_p2 | tmp_428_fu_4101_p3);

assign or_ln52_169_fu_4166_p2 = (xor_ln52_75_fu_4160_p2 | tmp_432_fu_4146_p3);

assign or_ln52_170_fu_4211_p2 = (xor_ln52_76_fu_4205_p2 | tmp_436_fu_4191_p3);

assign or_ln52_171_fu_4256_p2 = (xor_ln52_77_fu_4250_p2 | tmp_440_fu_4236_p3);

assign or_ln52_172_fu_4301_p2 = (xor_ln52_78_fu_4295_p2 | tmp_444_fu_4281_p3);

assign or_ln52_173_fu_4346_p2 = (xor_ln52_79_fu_4340_p2 | tmp_448_fu_4326_p3);

assign or_ln52_174_fu_4391_p2 = (xor_ln52_80_fu_4385_p2 | tmp_452_fu_4371_p3);

assign or_ln52_175_fu_4436_p2 = (xor_ln52_81_fu_4430_p2 | tmp_456_fu_4416_p3);

assign or_ln52_176_fu_4481_p2 = (xor_ln52_82_fu_4475_p2 | tmp_460_fu_4461_p3);

assign or_ln52_177_fu_4526_p2 = (xor_ln52_83_fu_4520_p2 | tmp_464_fu_4506_p3);

assign or_ln52_178_fu_4571_p2 = (xor_ln52_84_fu_4565_p2 | tmp_468_fu_4551_p3);

assign or_ln52_179_fu_4616_p2 = (xor_ln52_85_fu_4610_p2 | tmp_472_fu_4596_p3);

assign or_ln52_180_fu_4661_p2 = (xor_ln52_86_fu_4655_p2 | tmp_476_fu_4641_p3);

assign or_ln52_181_fu_4706_p2 = (xor_ln52_87_fu_4700_p2 | tmp_480_fu_4686_p3);

assign or_ln52_182_fu_4751_p2 = (xor_ln52_88_fu_4745_p2 | tmp_484_fu_4731_p3);

assign or_ln52_183_fu_4796_p2 = (xor_ln52_89_fu_4790_p2 | tmp_488_fu_4776_p3);

assign or_ln52_184_fu_4841_p2 = (xor_ln52_90_fu_4835_p2 | tmp_492_fu_4821_p3);

assign or_ln52_185_fu_4886_p2 = (xor_ln52_91_fu_4880_p2 | tmp_496_fu_4866_p3);

assign or_ln52_186_fu_4931_p2 = (xor_ln52_92_fu_4925_p2 | tmp_500_fu_4911_p3);

assign or_ln52_187_fu_4976_p2 = (xor_ln52_93_fu_4970_p2 | tmp_504_fu_4956_p3);

assign or_ln52_188_fu_5021_p2 = (xor_ln52_94_fu_5015_p2 | tmp_508_fu_5001_p3);

assign or_ln52_fu_902_p2 = (tmp_fu_876_p3 | icmp_ln52_fu_896_p2);

assign out_data_16_fu_3644_p3 = ((icmp_ln51_reg_5162[0:0] == 1'b1) ? out_data_fu_3637_p3 : 6'd0);

assign out_data_17_fu_3682_p3 = ((and_ln52_130_fu_3677_p2[0:0] == 1'b1) ? add_ln52_64_reg_5183 : 6'd63);

assign out_data_18_fu_3689_p3 = ((icmp_ln51_64_reg_5178[0:0] == 1'b1) ? out_data_17_fu_3682_p3 : 6'd0);

assign out_data_19_fu_3727_p3 = ((and_ln52_132_fu_3722_p2[0:0] == 1'b1) ? add_ln52_65_reg_5199 : 6'd63);

assign out_data_20_fu_3734_p3 = ((icmp_ln51_65_reg_5194[0:0] == 1'b1) ? out_data_19_fu_3727_p3 : 6'd0);

assign out_data_21_fu_3772_p3 = ((and_ln52_134_fu_3767_p2[0:0] == 1'b1) ? add_ln52_66_reg_5215 : 6'd63);

assign out_data_22_fu_3779_p3 = ((icmp_ln51_66_reg_5210[0:0] == 1'b1) ? out_data_21_fu_3772_p3 : 6'd0);

assign out_data_23_fu_3817_p3 = ((and_ln52_136_fu_3812_p2[0:0] == 1'b1) ? add_ln52_67_reg_5231 : 6'd63);

assign out_data_24_fu_3824_p3 = ((icmp_ln51_67_reg_5226[0:0] == 1'b1) ? out_data_23_fu_3817_p3 : 6'd0);

assign out_data_25_fu_3862_p3 = ((and_ln52_138_fu_3857_p2[0:0] == 1'b1) ? add_ln52_68_reg_5247 : 6'd63);

assign out_data_26_fu_3869_p3 = ((icmp_ln51_68_reg_5242[0:0] == 1'b1) ? out_data_25_fu_3862_p3 : 6'd0);

assign out_data_27_fu_3907_p3 = ((and_ln52_140_fu_3902_p2[0:0] == 1'b1) ? add_ln52_69_reg_5263 : 6'd63);

assign out_data_28_fu_3914_p3 = ((icmp_ln51_69_reg_5258[0:0] == 1'b1) ? out_data_27_fu_3907_p3 : 6'd0);

assign out_data_29_fu_3952_p3 = ((and_ln52_142_fu_3947_p2[0:0] == 1'b1) ? add_ln52_70_reg_5279 : 6'd63);

assign out_data_30_fu_3959_p3 = ((icmp_ln51_70_reg_5274[0:0] == 1'b1) ? out_data_29_fu_3952_p3 : 6'd0);

assign out_data_fu_3637_p3 = ((and_ln52_128_fu_3632_p2[0:0] == 1'b1) ? add_ln52_reg_5167 : 6'd63);

assign select_ln51_72_fu_4049_p3 = ((icmp_ln51_72_reg_5306[0:0] == 1'b1) ? select_ln52_72_fu_4042_p3 : 6'd0);

assign select_ln51_73_fu_4094_p3 = ((icmp_ln51_73_reg_5322[0:0] == 1'b1) ? select_ln52_73_fu_4087_p3 : 6'd0);

assign select_ln51_74_fu_4139_p3 = ((icmp_ln51_74_reg_5338[0:0] == 1'b1) ? select_ln52_74_fu_4132_p3 : 6'd0);

assign select_ln51_75_fu_4184_p3 = ((icmp_ln51_75_reg_5354[0:0] == 1'b1) ? select_ln52_75_fu_4177_p3 : 6'd0);

assign select_ln51_76_fu_4229_p3 = ((icmp_ln51_76_reg_5370[0:0] == 1'b1) ? select_ln52_76_fu_4222_p3 : 6'd0);

assign select_ln51_77_fu_4274_p3 = ((icmp_ln51_77_reg_5386[0:0] == 1'b1) ? select_ln52_77_fu_4267_p3 : 6'd0);

assign select_ln51_78_fu_4319_p3 = ((icmp_ln51_78_reg_5402[0:0] == 1'b1) ? select_ln52_78_fu_4312_p3 : 6'd0);

assign select_ln51_79_fu_4364_p3 = ((icmp_ln51_79_reg_5418[0:0] == 1'b1) ? select_ln52_79_fu_4357_p3 : 6'd0);

assign select_ln51_80_fu_4409_p3 = ((icmp_ln51_80_reg_5434[0:0] == 1'b1) ? select_ln52_80_fu_4402_p3 : 6'd0);

assign select_ln51_81_fu_4454_p3 = ((icmp_ln51_81_reg_5450[0:0] == 1'b1) ? select_ln52_81_fu_4447_p3 : 6'd0);

assign select_ln51_82_fu_4499_p3 = ((icmp_ln51_82_reg_5466[0:0] == 1'b1) ? select_ln52_82_fu_4492_p3 : 6'd0);

assign select_ln51_83_fu_4544_p3 = ((icmp_ln51_83_reg_5482[0:0] == 1'b1) ? select_ln52_83_fu_4537_p3 : 6'd0);

assign select_ln51_84_fu_4589_p3 = ((icmp_ln51_84_reg_5498[0:0] == 1'b1) ? select_ln52_84_fu_4582_p3 : 6'd0);

assign select_ln51_85_fu_4634_p3 = ((icmp_ln51_85_reg_5514[0:0] == 1'b1) ? select_ln52_85_fu_4627_p3 : 6'd0);

assign select_ln51_86_fu_4679_p3 = ((icmp_ln51_86_reg_5530[0:0] == 1'b1) ? select_ln52_86_fu_4672_p3 : 6'd0);

assign select_ln51_87_fu_4724_p3 = ((icmp_ln51_87_reg_5546[0:0] == 1'b1) ? select_ln52_87_fu_4717_p3 : 6'd0);

assign select_ln51_88_fu_4769_p3 = ((icmp_ln51_88_reg_5562[0:0] == 1'b1) ? select_ln52_88_fu_4762_p3 : 6'd0);

assign select_ln51_89_fu_4814_p3 = ((icmp_ln51_89_reg_5578[0:0] == 1'b1) ? select_ln52_89_fu_4807_p3 : 6'd0);

assign select_ln51_90_fu_4859_p3 = ((icmp_ln51_90_reg_5594[0:0] == 1'b1) ? select_ln52_90_fu_4852_p3 : 6'd0);

assign select_ln51_91_fu_4904_p3 = ((icmp_ln51_91_reg_5610[0:0] == 1'b1) ? select_ln52_91_fu_4897_p3 : 6'd0);

assign select_ln51_92_fu_4949_p3 = ((icmp_ln51_92_reg_5626[0:0] == 1'b1) ? select_ln52_92_fu_4942_p3 : 6'd0);

assign select_ln51_93_fu_4994_p3 = ((icmp_ln51_93_reg_5642[0:0] == 1'b1) ? select_ln52_93_fu_4987_p3 : 6'd0);

assign select_ln51_94_fu_5039_p3 = ((icmp_ln51_94_reg_5658[0:0] == 1'b1) ? select_ln52_94_fu_5032_p3 : 6'd0);

assign select_ln51_fu_4004_p3 = ((icmp_ln51_71_reg_5290[0:0] == 1'b1) ? select_ln52_fu_3997_p3 : 6'd0);

assign select_ln52_72_fu_4042_p3 = ((and_ln52_146_fu_4037_p2[0:0] == 1'b1) ? add_ln52_72_reg_5311 : 6'd63);

assign select_ln52_73_fu_4087_p3 = ((and_ln52_148_fu_4082_p2[0:0] == 1'b1) ? add_ln52_73_reg_5327 : 6'd63);

assign select_ln52_74_fu_4132_p3 = ((and_ln52_150_fu_4127_p2[0:0] == 1'b1) ? add_ln52_74_reg_5343 : 6'd63);

assign select_ln52_75_fu_4177_p3 = ((and_ln52_152_fu_4172_p2[0:0] == 1'b1) ? add_ln52_75_reg_5359 : 6'd63);

assign select_ln52_76_fu_4222_p3 = ((and_ln52_154_fu_4217_p2[0:0] == 1'b1) ? add_ln52_76_reg_5375 : 6'd63);

assign select_ln52_77_fu_4267_p3 = ((and_ln52_156_fu_4262_p2[0:0] == 1'b1) ? add_ln52_77_reg_5391 : 6'd63);

assign select_ln52_78_fu_4312_p3 = ((and_ln52_158_fu_4307_p2[0:0] == 1'b1) ? add_ln52_78_reg_5407 : 6'd63);

assign select_ln52_79_fu_4357_p3 = ((and_ln52_160_fu_4352_p2[0:0] == 1'b1) ? add_ln52_79_reg_5423 : 6'd63);

assign select_ln52_80_fu_4402_p3 = ((and_ln52_162_fu_4397_p2[0:0] == 1'b1) ? add_ln52_80_reg_5439 : 6'd63);

assign select_ln52_81_fu_4447_p3 = ((and_ln52_164_fu_4442_p2[0:0] == 1'b1) ? add_ln52_81_reg_5455 : 6'd63);

assign select_ln52_82_fu_4492_p3 = ((and_ln52_166_fu_4487_p2[0:0] == 1'b1) ? add_ln52_82_reg_5471 : 6'd63);

assign select_ln52_83_fu_4537_p3 = ((and_ln52_168_fu_4532_p2[0:0] == 1'b1) ? add_ln52_83_reg_5487 : 6'd63);

assign select_ln52_84_fu_4582_p3 = ((and_ln52_170_fu_4577_p2[0:0] == 1'b1) ? add_ln52_84_reg_5503 : 6'd63);

assign select_ln52_85_fu_4627_p3 = ((and_ln52_172_fu_4622_p2[0:0] == 1'b1) ? add_ln52_85_reg_5519 : 6'd63);

assign select_ln52_86_fu_4672_p3 = ((and_ln52_174_fu_4667_p2[0:0] == 1'b1) ? add_ln52_86_reg_5535 : 6'd63);

assign select_ln52_87_fu_4717_p3 = ((and_ln52_176_fu_4712_p2[0:0] == 1'b1) ? add_ln52_87_reg_5551 : 6'd63);

assign select_ln52_88_fu_4762_p3 = ((and_ln52_178_fu_4757_p2[0:0] == 1'b1) ? add_ln52_88_reg_5567 : 6'd63);

assign select_ln52_89_fu_4807_p3 = ((and_ln52_180_fu_4802_p2[0:0] == 1'b1) ? add_ln52_89_reg_5583 : 6'd63);

assign select_ln52_90_fu_4852_p3 = ((and_ln52_182_fu_4847_p2[0:0] == 1'b1) ? add_ln52_90_reg_5599 : 6'd63);

assign select_ln52_91_fu_4897_p3 = ((and_ln52_184_fu_4892_p2[0:0] == 1'b1) ? add_ln52_91_reg_5615 : 6'd63);

assign select_ln52_92_fu_4942_p3 = ((and_ln52_186_fu_4937_p2[0:0] == 1'b1) ? add_ln52_92_reg_5631 : 6'd63);

assign select_ln52_93_fu_4987_p3 = ((and_ln52_188_fu_4982_p2[0:0] == 1'b1) ? add_ln52_93_reg_5647 : 6'd63);

assign select_ln52_94_fu_5032_p3 = ((and_ln52_190_fu_5027_p2[0:0] == 1'b1) ? add_ln52_94_reg_5663 : 6'd63);

assign select_ln52_fu_3997_p3 = ((and_ln52_144_fu_3992_p2[0:0] == 1'b1) ? add_ln52_71_reg_5295 : 6'd63);

assign start_out = real_start;

assign tmp_127_fu_972_p4 = {{layer5_out_dout[25:22]}};

assign tmp_128_fu_1010_p4 = {{layer5_out_dout[43:33]}};

assign tmp_129_fu_1058_p4 = {{layer5_out_dout[47:44]}};

assign tmp_130_fu_1096_p4 = {{layer5_out_dout[65:55]}};

assign tmp_131_fu_1144_p4 = {{layer5_out_dout[69:66]}};

assign tmp_132_fu_1182_p4 = {{layer5_out_dout[87:77]}};

assign tmp_133_fu_1230_p4 = {{layer5_out_dout[91:88]}};

assign tmp_134_fu_1268_p4 = {{layer5_out_dout[109:99]}};

assign tmp_135_fu_1316_p4 = {{layer5_out_dout[113:110]}};

assign tmp_136_fu_1354_p4 = {{layer5_out_dout[131:121]}};

assign tmp_137_fu_1402_p4 = {{layer5_out_dout[135:132]}};

assign tmp_138_fu_1440_p4 = {{layer5_out_dout[153:143]}};

assign tmp_139_fu_1488_p4 = {{layer5_out_dout[157:154]}};

assign tmp_140_fu_1526_p4 = {{layer5_out_dout[175:165]}};

assign tmp_141_fu_1574_p4 = {{layer5_out_dout[179:176]}};

assign tmp_142_fu_1612_p4 = {{layer5_out_dout[197:187]}};

assign tmp_143_fu_1660_p4 = {{layer5_out_dout[201:198]}};

assign tmp_144_fu_1698_p4 = {{layer5_out_dout[219:209]}};

assign tmp_145_fu_1746_p4 = {{layer5_out_dout[223:220]}};

assign tmp_146_fu_1784_p4 = {{layer5_out_dout[241:231]}};

assign tmp_147_fu_1832_p4 = {{layer5_out_dout[245:242]}};

assign tmp_148_fu_1870_p4 = {{layer5_out_dout[263:253]}};

assign tmp_149_fu_1918_p4 = {{layer5_out_dout[267:264]}};

assign tmp_150_fu_1956_p4 = {{layer5_out_dout[285:275]}};

assign tmp_151_fu_2004_p4 = {{layer5_out_dout[289:286]}};

assign tmp_152_fu_2042_p4 = {{layer5_out_dout[307:297]}};

assign tmp_153_fu_2090_p4 = {{layer5_out_dout[311:308]}};

assign tmp_154_fu_2128_p4 = {{layer5_out_dout[329:319]}};

assign tmp_155_fu_2176_p4 = {{layer5_out_dout[333:330]}};

assign tmp_156_fu_2214_p4 = {{layer5_out_dout[351:341]}};

assign tmp_157_fu_2262_p4 = {{layer5_out_dout[355:352]}};

assign tmp_158_fu_2300_p4 = {{layer5_out_dout[373:363]}};

assign tmp_159_fu_2348_p4 = {{layer5_out_dout[377:374]}};

assign tmp_160_fu_2386_p4 = {{layer5_out_dout[395:385]}};

assign tmp_161_fu_2434_p4 = {{layer5_out_dout[399:396]}};

assign tmp_162_fu_2472_p4 = {{layer5_out_dout[417:407]}};

assign tmp_163_fu_2520_p4 = {{layer5_out_dout[421:418]}};

assign tmp_164_fu_2558_p4 = {{layer5_out_dout[439:429]}};

assign tmp_165_fu_2606_p4 = {{layer5_out_dout[443:440]}};

assign tmp_166_fu_2644_p4 = {{layer5_out_dout[461:451]}};

assign tmp_167_fu_2692_p4 = {{layer5_out_dout[465:462]}};

assign tmp_168_fu_2730_p4 = {{layer5_out_dout[483:473]}};

assign tmp_169_fu_2778_p4 = {{layer5_out_dout[487:484]}};

assign tmp_170_fu_2816_p4 = {{layer5_out_dout[505:495]}};

assign tmp_171_fu_2864_p4 = {{layer5_out_dout[509:506]}};

assign tmp_172_fu_2902_p4 = {{layer5_out_dout[527:517]}};

assign tmp_173_fu_2950_p4 = {{layer5_out_dout[531:528]}};

assign tmp_174_fu_2988_p4 = {{layer5_out_dout[549:539]}};

assign tmp_175_fu_3036_p4 = {{layer5_out_dout[553:550]}};

assign tmp_176_fu_3074_p4 = {{layer5_out_dout[571:561]}};

assign tmp_177_fu_3122_p4 = {{layer5_out_dout[575:572]}};

assign tmp_178_fu_3160_p4 = {{layer5_out_dout[593:583]}};

assign tmp_179_fu_3208_p4 = {{layer5_out_dout[597:594]}};

assign tmp_180_fu_3246_p4 = {{layer5_out_dout[615:605]}};

assign tmp_181_fu_3294_p4 = {{layer5_out_dout[619:616]}};

assign tmp_182_fu_3332_p4 = {{layer5_out_dout[637:627]}};

assign tmp_183_fu_3380_p4 = {{layer5_out_dout[641:638]}};

assign tmp_184_fu_3418_p4 = {{layer5_out_dout[659:649]}};

assign tmp_185_fu_3466_p4 = {{layer5_out_dout[663:660]}};

assign tmp_186_fu_3504_p4 = {{layer5_out_dout[681:671]}};

assign tmp_187_fu_3552_p4 = {{layer5_out_dout[685:682]}};

assign tmp_188_fu_3590_p4 = {{layer5_out_dout[703:693]}};

assign tmp_383_fu_884_p3 = layer5_out_dout[32'd4];

assign tmp_384_fu_3606_p3 = add_ln52_reg_5167[32'd5];

assign tmp_385_fu_3613_p3 = layer5_out_read_reg_5126[32'd10];

assign tmp_386_fu_956_p3 = layer5_out_dout[32'd27];

assign tmp_387_fu_964_p3 = layer5_out_dout[32'd26];

assign tmp_388_fu_3651_p3 = add_ln52_64_reg_5183[32'd5];

assign tmp_389_fu_3658_p3 = layer5_out_read_reg_5126[32'd32];

assign tmp_390_fu_1042_p3 = layer5_out_dout[32'd49];

assign tmp_391_fu_1050_p3 = layer5_out_dout[32'd48];

assign tmp_392_fu_3696_p3 = add_ln52_65_reg_5199[32'd5];

assign tmp_393_fu_3703_p3 = layer5_out_read_reg_5126[32'd54];

assign tmp_394_fu_1128_p3 = layer5_out_dout[32'd71];

assign tmp_395_fu_1136_p3 = layer5_out_dout[32'd70];

assign tmp_396_fu_3741_p3 = add_ln52_66_reg_5215[32'd5];

assign tmp_397_fu_3748_p3 = layer5_out_read_reg_5126[32'd76];

assign tmp_398_fu_1214_p3 = layer5_out_dout[32'd93];

assign tmp_399_fu_1222_p3 = layer5_out_dout[32'd92];

assign tmp_400_fu_3786_p3 = add_ln52_67_reg_5231[32'd5];

assign tmp_401_fu_3793_p3 = layer5_out_read_reg_5126[32'd98];

assign tmp_402_fu_1300_p3 = layer5_out_dout[32'd115];

assign tmp_403_fu_1308_p3 = layer5_out_dout[32'd114];

assign tmp_404_fu_3831_p3 = add_ln52_68_reg_5247[32'd5];

assign tmp_405_fu_3838_p3 = layer5_out_read_reg_5126[32'd120];

assign tmp_406_fu_1386_p3 = layer5_out_dout[32'd137];

assign tmp_407_fu_1394_p3 = layer5_out_dout[32'd136];

assign tmp_408_fu_3876_p3 = add_ln52_69_reg_5263[32'd5];

assign tmp_409_fu_3883_p3 = layer5_out_read_reg_5126[32'd142];

assign tmp_410_fu_1472_p3 = layer5_out_dout[32'd159];

assign tmp_411_fu_1480_p3 = layer5_out_dout[32'd158];

assign tmp_412_fu_3921_p3 = add_ln52_70_reg_5279[32'd5];

assign tmp_413_fu_3928_p3 = layer5_out_read_reg_5126[32'd164];

assign tmp_414_fu_1558_p3 = layer5_out_dout[32'd181];

assign tmp_415_fu_1566_p3 = layer5_out_dout[32'd180];

assign tmp_416_fu_3966_p3 = add_ln52_71_reg_5295[32'd5];

assign tmp_417_fu_3973_p3 = layer5_out_read_reg_5126[32'd186];

assign tmp_418_fu_1644_p3 = layer5_out_dout[32'd203];

assign tmp_419_fu_1652_p3 = layer5_out_dout[32'd202];

assign tmp_420_fu_4011_p3 = add_ln52_72_reg_5311[32'd5];

assign tmp_421_fu_4018_p3 = layer5_out_read_reg_5126[32'd208];

assign tmp_422_fu_1730_p3 = layer5_out_dout[32'd225];

assign tmp_423_fu_1738_p3 = layer5_out_dout[32'd224];

assign tmp_424_fu_4056_p3 = add_ln52_73_reg_5327[32'd5];

assign tmp_425_fu_4063_p3 = layer5_out_read_reg_5126[32'd230];

assign tmp_426_fu_1816_p3 = layer5_out_dout[32'd247];

assign tmp_427_fu_1824_p3 = layer5_out_dout[32'd246];

assign tmp_428_fu_4101_p3 = add_ln52_74_reg_5343[32'd5];

assign tmp_429_fu_4108_p3 = layer5_out_read_reg_5126[32'd252];

assign tmp_430_fu_1902_p3 = layer5_out_dout[32'd269];

assign tmp_431_fu_1910_p3 = layer5_out_dout[32'd268];

assign tmp_432_fu_4146_p3 = add_ln52_75_reg_5359[32'd5];

assign tmp_433_fu_4153_p3 = layer5_out_read_reg_5126[32'd274];

assign tmp_434_fu_1988_p3 = layer5_out_dout[32'd291];

assign tmp_435_fu_1996_p3 = layer5_out_dout[32'd290];

assign tmp_436_fu_4191_p3 = add_ln52_76_reg_5375[32'd5];

assign tmp_437_fu_4198_p3 = layer5_out_read_reg_5126[32'd296];

assign tmp_438_fu_2074_p3 = layer5_out_dout[32'd313];

assign tmp_439_fu_2082_p3 = layer5_out_dout[32'd312];

assign tmp_440_fu_4236_p3 = add_ln52_77_reg_5391[32'd5];

assign tmp_441_fu_4243_p3 = layer5_out_read_reg_5126[32'd318];

assign tmp_442_fu_2160_p3 = layer5_out_dout[32'd335];

assign tmp_443_fu_2168_p3 = layer5_out_dout[32'd334];

assign tmp_444_fu_4281_p3 = add_ln52_78_reg_5407[32'd5];

assign tmp_445_fu_4288_p3 = layer5_out_read_reg_5126[32'd340];

assign tmp_446_fu_2246_p3 = layer5_out_dout[32'd357];

assign tmp_447_fu_2254_p3 = layer5_out_dout[32'd356];

assign tmp_448_fu_4326_p3 = add_ln52_79_reg_5423[32'd5];

assign tmp_449_fu_4333_p3 = layer5_out_read_reg_5126[32'd362];

assign tmp_450_fu_2332_p3 = layer5_out_dout[32'd379];

assign tmp_451_fu_2340_p3 = layer5_out_dout[32'd378];

assign tmp_452_fu_4371_p3 = add_ln52_80_reg_5439[32'd5];

assign tmp_453_fu_4378_p3 = layer5_out_read_reg_5126[32'd384];

assign tmp_454_fu_2418_p3 = layer5_out_dout[32'd401];

assign tmp_455_fu_2426_p3 = layer5_out_dout[32'd400];

assign tmp_456_fu_4416_p3 = add_ln52_81_reg_5455[32'd5];

assign tmp_457_fu_4423_p3 = layer5_out_read_reg_5126[32'd406];

assign tmp_458_fu_2504_p3 = layer5_out_dout[32'd423];

assign tmp_459_fu_2512_p3 = layer5_out_dout[32'd422];

assign tmp_460_fu_4461_p3 = add_ln52_82_reg_5471[32'd5];

assign tmp_461_fu_4468_p3 = layer5_out_read_reg_5126[32'd428];

assign tmp_462_fu_2590_p3 = layer5_out_dout[32'd445];

assign tmp_463_fu_2598_p3 = layer5_out_dout[32'd444];

assign tmp_464_fu_4506_p3 = add_ln52_83_reg_5487[32'd5];

assign tmp_465_fu_4513_p3 = layer5_out_read_reg_5126[32'd450];

assign tmp_466_fu_2676_p3 = layer5_out_dout[32'd467];

assign tmp_467_fu_2684_p3 = layer5_out_dout[32'd466];

assign tmp_468_fu_4551_p3 = add_ln52_84_reg_5503[32'd5];

assign tmp_469_fu_4558_p3 = layer5_out_read_reg_5126[32'd472];

assign tmp_470_fu_2762_p3 = layer5_out_dout[32'd489];

assign tmp_471_fu_2770_p3 = layer5_out_dout[32'd488];

assign tmp_472_fu_4596_p3 = add_ln52_85_reg_5519[32'd5];

assign tmp_473_fu_4603_p3 = layer5_out_read_reg_5126[32'd494];

assign tmp_474_fu_2848_p3 = layer5_out_dout[32'd511];

assign tmp_475_fu_2856_p3 = layer5_out_dout[32'd510];

assign tmp_476_fu_4641_p3 = add_ln52_86_reg_5535[32'd5];

assign tmp_477_fu_4648_p3 = layer5_out_read_reg_5126[32'd516];

assign tmp_478_fu_2934_p3 = layer5_out_dout[32'd533];

assign tmp_479_fu_2942_p3 = layer5_out_dout[32'd532];

assign tmp_480_fu_4686_p3 = add_ln52_87_reg_5551[32'd5];

assign tmp_481_fu_4693_p3 = layer5_out_read_reg_5126[32'd538];

assign tmp_482_fu_3020_p3 = layer5_out_dout[32'd555];

assign tmp_483_fu_3028_p3 = layer5_out_dout[32'd554];

assign tmp_484_fu_4731_p3 = add_ln52_88_reg_5567[32'd5];

assign tmp_485_fu_4738_p3 = layer5_out_read_reg_5126[32'd560];

assign tmp_486_fu_3106_p3 = layer5_out_dout[32'd577];

assign tmp_487_fu_3114_p3 = layer5_out_dout[32'd576];

assign tmp_488_fu_4776_p3 = add_ln52_89_reg_5583[32'd5];

assign tmp_489_fu_4783_p3 = layer5_out_read_reg_5126[32'd582];

assign tmp_490_fu_3192_p3 = layer5_out_dout[32'd599];

assign tmp_491_fu_3200_p3 = layer5_out_dout[32'd598];

assign tmp_492_fu_4821_p3 = add_ln52_90_reg_5599[32'd5];

assign tmp_493_fu_4828_p3 = layer5_out_read_reg_5126[32'd604];

assign tmp_494_fu_3278_p3 = layer5_out_dout[32'd621];

assign tmp_495_fu_3286_p3 = layer5_out_dout[32'd620];

assign tmp_496_fu_4866_p3 = add_ln52_91_reg_5615[32'd5];

assign tmp_497_fu_4873_p3 = layer5_out_read_reg_5126[32'd626];

assign tmp_498_fu_3364_p3 = layer5_out_dout[32'd643];

assign tmp_499_fu_3372_p3 = layer5_out_dout[32'd642];

assign tmp_500_fu_4911_p3 = add_ln52_92_reg_5631[32'd5];

assign tmp_501_fu_4918_p3 = layer5_out_read_reg_5126[32'd648];

assign tmp_502_fu_3450_p3 = layer5_out_dout[32'd665];

assign tmp_503_fu_3458_p3 = layer5_out_dout[32'd664];

assign tmp_504_fu_4956_p3 = add_ln52_93_reg_5647[32'd5];

assign tmp_505_fu_4963_p3 = layer5_out_read_reg_5126[32'd670];

assign tmp_506_fu_3536_p3 = layer5_out_dout[32'd687];

assign tmp_507_fu_3544_p3 = layer5_out_dout[32'd686];

assign tmp_508_fu_5001_p3 = add_ln52_94_reg_5663[32'd5];

assign tmp_509_fu_5008_p3 = layer5_out_read_reg_5126[32'd692];

assign tmp_fu_876_p3 = layer5_out_dout[32'd5];

assign tmp_s_fu_924_p4 = {{layer5_out_dout[21:11]}};

assign trunc_ln44_63_fu_560_p4 = {{layer5_out_dout[703:682]}};

assign trunc_ln44_64_fu_570_p4 = {{layer5_out_dout[43:22]}};

assign trunc_ln44_65_fu_580_p4 = {{layer5_out_dout[65:44]}};

assign trunc_ln44_66_fu_590_p4 = {{layer5_out_dout[87:66]}};

assign trunc_ln44_67_fu_600_p4 = {{layer5_out_dout[109:88]}};

assign trunc_ln44_68_fu_610_p4 = {{layer5_out_dout[131:110]}};

assign trunc_ln44_69_fu_620_p4 = {{layer5_out_dout[153:132]}};

assign trunc_ln44_70_fu_630_p4 = {{layer5_out_dout[175:154]}};

assign trunc_ln44_71_fu_640_p4 = {{layer5_out_dout[197:176]}};

assign trunc_ln44_72_fu_650_p4 = {{layer5_out_dout[219:198]}};

assign trunc_ln44_73_fu_660_p4 = {{layer5_out_dout[241:220]}};

assign trunc_ln44_74_fu_670_p4 = {{layer5_out_dout[263:242]}};

assign trunc_ln44_75_fu_680_p4 = {{layer5_out_dout[285:264]}};

assign trunc_ln44_76_fu_690_p4 = {{layer5_out_dout[307:286]}};

assign trunc_ln44_77_fu_700_p4 = {{layer5_out_dout[329:308]}};

assign trunc_ln44_78_fu_710_p4 = {{layer5_out_dout[351:330]}};

assign trunc_ln44_79_fu_720_p4 = {{layer5_out_dout[373:352]}};

assign trunc_ln44_80_fu_730_p4 = {{layer5_out_dout[395:374]}};

assign trunc_ln44_81_fu_740_p4 = {{layer5_out_dout[417:396]}};

assign trunc_ln44_82_fu_750_p4 = {{layer5_out_dout[439:418]}};

assign trunc_ln44_83_fu_760_p4 = {{layer5_out_dout[461:440]}};

assign trunc_ln44_84_fu_770_p4 = {{layer5_out_dout[483:462]}};

assign trunc_ln44_85_fu_780_p4 = {{layer5_out_dout[505:484]}};

assign trunc_ln44_86_fu_790_p4 = {{layer5_out_dout[527:506]}};

assign trunc_ln44_87_fu_800_p4 = {{layer5_out_dout[549:528]}};

assign trunc_ln44_88_fu_810_p4 = {{layer5_out_dout[571:550]}};

assign trunc_ln44_89_fu_820_p4 = {{layer5_out_dout[593:572]}};

assign trunc_ln44_90_fu_830_p4 = {{layer5_out_dout[615:594]}};

assign trunc_ln44_91_fu_840_p4 = {{layer5_out_dout[637:616]}};

assign trunc_ln44_92_fu_850_p4 = {{layer5_out_dout[659:638]}};

assign trunc_ln44_fu_546_p1 = layer5_out_dout[21:0];

assign trunc_ln44_s_fu_550_p4 = {{layer5_out_dout[681:660]}};

assign trunc_ln4_fu_866_p4 = {{layer5_out_dout[10:5]}};

assign trunc_ln52_63_fu_1032_p4 = {{layer5_out_dout[54:49]}};

assign trunc_ln52_64_fu_1118_p4 = {{layer5_out_dout[76:71]}};

assign trunc_ln52_65_fu_1204_p4 = {{layer5_out_dout[98:93]}};

assign trunc_ln52_66_fu_1290_p4 = {{layer5_out_dout[120:115]}};

assign trunc_ln52_67_fu_1376_p4 = {{layer5_out_dout[142:137]}};

assign trunc_ln52_68_fu_1462_p4 = {{layer5_out_dout[164:159]}};

assign trunc_ln52_69_fu_1548_p4 = {{layer5_out_dout[186:181]}};

assign trunc_ln52_70_fu_1634_p4 = {{layer5_out_dout[208:203]}};

assign trunc_ln52_71_fu_1720_p4 = {{layer5_out_dout[230:225]}};

assign trunc_ln52_72_fu_1806_p4 = {{layer5_out_dout[252:247]}};

assign trunc_ln52_73_fu_1892_p4 = {{layer5_out_dout[274:269]}};

assign trunc_ln52_74_fu_1978_p4 = {{layer5_out_dout[296:291]}};

assign trunc_ln52_75_fu_2064_p4 = {{layer5_out_dout[318:313]}};

assign trunc_ln52_76_fu_2150_p4 = {{layer5_out_dout[340:335]}};

assign trunc_ln52_77_fu_2236_p4 = {{layer5_out_dout[362:357]}};

assign trunc_ln52_78_fu_2322_p4 = {{layer5_out_dout[384:379]}};

assign trunc_ln52_79_fu_2408_p4 = {{layer5_out_dout[406:401]}};

assign trunc_ln52_80_fu_2494_p4 = {{layer5_out_dout[428:423]}};

assign trunc_ln52_81_fu_2580_p4 = {{layer5_out_dout[450:445]}};

assign trunc_ln52_82_fu_2666_p4 = {{layer5_out_dout[472:467]}};

assign trunc_ln52_83_fu_2752_p4 = {{layer5_out_dout[494:489]}};

assign trunc_ln52_84_fu_2838_p4 = {{layer5_out_dout[516:511]}};

assign trunc_ln52_85_fu_2924_p4 = {{layer5_out_dout[538:533]}};

assign trunc_ln52_86_fu_3010_p4 = {{layer5_out_dout[560:555]}};

assign trunc_ln52_87_fu_3096_p4 = {{layer5_out_dout[582:577]}};

assign trunc_ln52_88_fu_3182_p4 = {{layer5_out_dout[604:599]}};

assign trunc_ln52_89_fu_3268_p4 = {{layer5_out_dout[626:621]}};

assign trunc_ln52_90_fu_3354_p4 = {{layer5_out_dout[648:643]}};

assign trunc_ln52_91_fu_3440_p4 = {{layer5_out_dout[670:665]}};

assign trunc_ln52_92_fu_3526_p4 = {{layer5_out_dout[692:687]}};

assign trunc_ln52_fu_892_p1 = layer5_out_dout[3:0];

assign trunc_ln52_s_fu_946_p4 = {{layer5_out_dout[32:27]}};

assign xor_ln52_64_fu_3665_p2 = (tmp_389_fu_3658_p3 ^ 1'd1);

assign xor_ln52_65_fu_3710_p2 = (tmp_393_fu_3703_p3 ^ 1'd1);

assign xor_ln52_66_fu_3755_p2 = (tmp_397_fu_3748_p3 ^ 1'd1);

assign xor_ln52_67_fu_3800_p2 = (tmp_401_fu_3793_p3 ^ 1'd1);

assign xor_ln52_68_fu_3845_p2 = (tmp_405_fu_3838_p3 ^ 1'd1);

assign xor_ln52_69_fu_3890_p2 = (tmp_409_fu_3883_p3 ^ 1'd1);

assign xor_ln52_70_fu_3935_p2 = (tmp_413_fu_3928_p3 ^ 1'd1);

assign xor_ln52_71_fu_3980_p2 = (tmp_417_fu_3973_p3 ^ 1'd1);

assign xor_ln52_72_fu_4025_p2 = (tmp_421_fu_4018_p3 ^ 1'd1);

assign xor_ln52_73_fu_4070_p2 = (tmp_425_fu_4063_p3 ^ 1'd1);

assign xor_ln52_74_fu_4115_p2 = (tmp_429_fu_4108_p3 ^ 1'd1);

assign xor_ln52_75_fu_4160_p2 = (tmp_433_fu_4153_p3 ^ 1'd1);

assign xor_ln52_76_fu_4205_p2 = (tmp_437_fu_4198_p3 ^ 1'd1);

assign xor_ln52_77_fu_4250_p2 = (tmp_441_fu_4243_p3 ^ 1'd1);

assign xor_ln52_78_fu_4295_p2 = (tmp_445_fu_4288_p3 ^ 1'd1);

assign xor_ln52_79_fu_4340_p2 = (tmp_449_fu_4333_p3 ^ 1'd1);

assign xor_ln52_80_fu_4385_p2 = (tmp_453_fu_4378_p3 ^ 1'd1);

assign xor_ln52_81_fu_4430_p2 = (tmp_457_fu_4423_p3 ^ 1'd1);

assign xor_ln52_82_fu_4475_p2 = (tmp_461_fu_4468_p3 ^ 1'd1);

assign xor_ln52_83_fu_4520_p2 = (tmp_465_fu_4513_p3 ^ 1'd1);

assign xor_ln52_84_fu_4565_p2 = (tmp_469_fu_4558_p3 ^ 1'd1);

assign xor_ln52_85_fu_4610_p2 = (tmp_473_fu_4603_p3 ^ 1'd1);

assign xor_ln52_86_fu_4655_p2 = (tmp_477_fu_4648_p3 ^ 1'd1);

assign xor_ln52_87_fu_4700_p2 = (tmp_481_fu_4693_p3 ^ 1'd1);

assign xor_ln52_88_fu_4745_p2 = (tmp_485_fu_4738_p3 ^ 1'd1);

assign xor_ln52_89_fu_4790_p2 = (tmp_489_fu_4783_p3 ^ 1'd1);

assign xor_ln52_90_fu_4835_p2 = (tmp_493_fu_4828_p3 ^ 1'd1);

assign xor_ln52_91_fu_4880_p2 = (tmp_497_fu_4873_p3 ^ 1'd1);

assign xor_ln52_92_fu_4925_p2 = (tmp_501_fu_4918_p3 ^ 1'd1);

assign xor_ln52_93_fu_4970_p2 = (tmp_505_fu_4963_p3 ^ 1'd1);

assign xor_ln52_94_fu_5015_p2 = (tmp_509_fu_5008_p3 ^ 1'd1);

assign xor_ln52_fu_3620_p2 = (tmp_385_fu_3613_p3 ^ 1'd1);

assign zext_ln52_64_fu_1000_p1 = and_ln52_129_fu_994_p2;

assign zext_ln52_65_fu_1086_p1 = and_ln52_131_fu_1080_p2;

assign zext_ln52_66_fu_1172_p1 = and_ln52_133_fu_1166_p2;

assign zext_ln52_67_fu_1258_p1 = and_ln52_135_fu_1252_p2;

assign zext_ln52_68_fu_1344_p1 = and_ln52_137_fu_1338_p2;

assign zext_ln52_69_fu_1430_p1 = and_ln52_139_fu_1424_p2;

assign zext_ln52_70_fu_1516_p1 = and_ln52_141_fu_1510_p2;

assign zext_ln52_71_fu_1602_p1 = and_ln52_143_fu_1596_p2;

assign zext_ln52_72_fu_1688_p1 = and_ln52_145_fu_1682_p2;

assign zext_ln52_73_fu_1774_p1 = and_ln52_147_fu_1768_p2;

assign zext_ln52_74_fu_1860_p1 = and_ln52_149_fu_1854_p2;

assign zext_ln52_75_fu_1946_p1 = and_ln52_151_fu_1940_p2;

assign zext_ln52_76_fu_2032_p1 = and_ln52_153_fu_2026_p2;

assign zext_ln52_77_fu_2118_p1 = and_ln52_155_fu_2112_p2;

assign zext_ln52_78_fu_2204_p1 = and_ln52_157_fu_2198_p2;

assign zext_ln52_79_fu_2290_p1 = and_ln52_159_fu_2284_p2;

assign zext_ln52_80_fu_2376_p1 = and_ln52_161_fu_2370_p2;

assign zext_ln52_81_fu_2462_p1 = and_ln52_163_fu_2456_p2;

assign zext_ln52_82_fu_2548_p1 = and_ln52_165_fu_2542_p2;

assign zext_ln52_83_fu_2634_p1 = and_ln52_167_fu_2628_p2;

assign zext_ln52_84_fu_2720_p1 = and_ln52_169_fu_2714_p2;

assign zext_ln52_85_fu_2806_p1 = and_ln52_171_fu_2800_p2;

assign zext_ln52_86_fu_2892_p1 = and_ln52_173_fu_2886_p2;

assign zext_ln52_87_fu_2978_p1 = and_ln52_175_fu_2972_p2;

assign zext_ln52_88_fu_3064_p1 = and_ln52_177_fu_3058_p2;

assign zext_ln52_89_fu_3150_p1 = and_ln52_179_fu_3144_p2;

assign zext_ln52_90_fu_3236_p1 = and_ln52_181_fu_3230_p2;

assign zext_ln52_91_fu_3322_p1 = and_ln52_183_fu_3316_p2;

assign zext_ln52_92_fu_3408_p1 = and_ln52_185_fu_3402_p2;

assign zext_ln52_93_fu_3494_p1 = and_ln52_187_fu_3488_p2;

assign zext_ln52_94_fu_3580_p1 = and_ln52_189_fu_3574_p2;

assign zext_ln52_fu_914_p1 = and_ln52_fu_908_p2;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_ufixed_6_0_4_0_0_32u_relu_config7_s
