Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_9:
      Precision:
        result: ap_fixed<16,10>
      Trace: false
    q_activation_33:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_34:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_35:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_36:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: ap_fixed<16,10>
        slope: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_33:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_33_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_34:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_34_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_35:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_35_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_36:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,10>
        bias: fixed<8,3>
        result: ap_fixed<16,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_36_linear:
      Precision:
        result: ap_fixed<16,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,10>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'no_opt_150_8<16,10>/keras_model.h5'
OutputDir: no_opt_150_8<16,10>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 1d20f8Ab
Version: 1.0.0
