Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    activation_3:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    activation_4:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    activation_5:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    activation_6:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_13:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    conv1d_13_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_14:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    conv1d_14_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_15:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    conv1d_15_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_16:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    conv1d_16_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    input_4:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'no_opt_150_8_regular<16,6>/keras_model.h5'
OutputDir: no_opt_150_8_regular<16,6>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: bBefDB67
Version: 1.0.0
