Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_4:
      Precision:
        result: ap_fixed<20,10>
      Trace: false
    q_activation_15:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_16:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_17:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_18:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_19:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: ap_fixed<20,10>
        slope: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_15:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,10>
        bias: fixed<8,3>
        result: ap_fixed<20,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_15_linear:
      Precision:
        result: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_16:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,10>
        bias: fixed<8,3>
        result: ap_fixed<20,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_16_linear:
      Precision:
        result: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_17:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,10>
        bias: fixed<8,3>
        result: ap_fixed<20,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_17_linear:
      Precision:
        result: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_18:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,10>
        bias: fixed<8,3>
        result: ap_fixed<20,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_18_linear:
      Precision:
        result: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_19:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,10>
        bias: fixed<8,3>
        result: ap_fixed<20,10>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_19_linear:
      Precision:
        result: ap_fixed<20,10>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<20,10>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model '../HLS_models/Qdiluted_64<20,10>/keras_model.h5'
OutputDir: ../HLS_models/Qdiluted_64<20,10>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 613F0302
Version: 1.0.0
