Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_2:
      Precision:
        result: ap_fixed<16,8>
      Trace: false
    q_activation_5:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_6:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_7:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_8:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_9:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: ap_fixed<16,8>
        slope: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_5:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,8>
        bias: fixed<8,3>
        result: ap_fixed<16,8>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_5_linear:
      Precision:
        result: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_6:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,8>
        bias: fixed<8,3>
        result: ap_fixed<16,8>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_6_linear:
      Precision:
        result: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_7:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,8>
        bias: fixed<8,3>
        result: ap_fixed<16,8>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_7_linear:
      Precision:
        result: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_8:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,8>
        bias: fixed<8,3>
        result: ap_fixed<16,8>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_8_linear:
      Precision:
        result: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_9:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,8>
        bias: fixed<8,3>
        result: ap_fixed<16,8>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_9_linear:
      Precision:
        result: ap_fixed<16,8>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,8>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'dil_150_unpruned<16,8>/keras_model.h5'
OutputDir: dil_150_unpruned<16,8>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: dFeE5b0E
Version: 1.0.0
