Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_14:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    q_activation_65:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_66:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_67:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_68:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_activation_69:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
        shift: ap_fixed<16,6>
        slope: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_65:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: fixed<8,3>
        result: ap_fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_65_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_66:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: fixed<8,3>
        result: ap_fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_66_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_67:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: fixed<8,3>
        result: ap_fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_67_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_68:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: fixed<8,3>
        result: ap_fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_68_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_conv1d_69:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<16,6>
        bias: fixed<8,3>
        result: ap_fixed<16,6>
        weight: fixed<8,3>
      ReuseFactor: 1
      Trace: false
    q_conv1d_69_linear:
      Precision:
        result: ap_fixed<16,6>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    zero_padding1d_22:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    zero_padding1d_23:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    zero_padding1d_24:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    zero_padding1d_25:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'dil_150_unpruned_16_valid<16,6>/keras_model.h5'
OutputDir: dil_150_unpruned_16_valid<16,6>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 74cFB29A
Version: 1.0.0
