Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    activation_7:
      Precision:
        result: ap_fixed<20,2>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_17:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,2>
        bias: ap_fixed<20,2>
        result: ap_fixed<20,2>
        weight: ap_fixed<20,2>
      ReuseFactor: 1
      Trace: false
    conv1d_17_relu:
      Precision:
        result: ap_fixed<20,2>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_18:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,2>
        bias: ap_fixed<20,2>
        result: ap_fixed<20,2>
        weight: ap_fixed<20,2>
      ReuseFactor: 1
      Trace: false
    conv1d_18_linear:
      Precision:
        result: ap_fixed<20,2>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_19:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,2>
        bias: ap_fixed<20,2>
        result: ap_fixed<20,2>
        weight: ap_fixed<20,2>
      ReuseFactor: 1
      Trace: false
    conv1d_19_linear:
      Precision:
        result: ap_fixed<20,2>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    conv1d_20:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      Precision:
        accum: ap_fixed<20,2>
        bias: ap_fixed<20,2>
        result: ap_fixed<20,2>
        weight: ap_fixed<20,2>
      ReuseFactor: 1
      Trace: false
    conv1d_20_linear:
      Precision:
        result: ap_fixed<20,2>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    input_5:
      Precision:
        result: ap_fixed<20,2>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<20,2>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'HLS_models/no_opt_150_8_regular<20,2>/keras_model.h5'
OutputDir: HLS_models/no_opt_150_8_regular<20,2>
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 3BadCe7e
Version: 1.0.0
